stages:
  - lint
  - test
  - build

variables:
  GO_VERSION: "1.25"

lint:
  image: golangci/golangci-lint:v1.55.2
  stage: lint
  script:
    - golangci-lint run ./...
  allow_failure: true

test:
  image: golang:$GO_VERSION
  stage: test
  script:
    - go test -v -race ./...

build_services:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker build -t api_gateway -f cmd/api_gateway/Dockerfile .
    - docker build -t project_service -f cmd/project_service/Dockerfile .
