run:
  timeout: 10m
  go: '1.25'
  tests: true
  skip-dirs:
    - pkg/protobuf
    - third_party

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: wire_gen\.go
      linters:
        - unused
