// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package workflow

import (
	"github.com/lucky720s/diplomaflow/pkg/database"
	"github.com/lucky720s/diplomaflow/pkg/logger"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(cfg *Config, log *logger.Logger) (*Handler, func(), error) {
	db, cleanup, err := ProvideDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	workflowRepository := NewRepository(db)
	service := NewService(workflowRepository)
	handler := NewHandler(service)
	return handler, func() {
		cleanup()
	}, nil
}

// wire.go:

func ProvideDB(cfg *Config) (*gorm.DB, func(), error) {
	return database.NewConnection(cfg.Database.DSN)
}
