// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package workflow

import (
	"github.com/lucky720s/diplomaflow/pkg/database"
	"github.com/lucky720s/diplomaflow/pkg/logger"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(cfg *Config, log *logger.Logger) (*Handler, func(), error) {
	db, cleanup, err := ProvideDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	workflowRepository := ProvideRepository(db)
	zapLogger := ProvideLogger(log)
	service := ProvideService(workflowRepository, zapLogger)
	handler := ProvideHandler(service, zapLogger)
	return handler, func() {
		cleanup()
	}, nil
}

// wire.go:

func ProvideDB(cfg *Config) (*gorm.DB, func(), error) {
	return database.NewConnection(cfg.Database.DSN)
}

func ProvideLogger(log *logger.Logger) *zap.Logger {
	return log.Logger
}

func ProvideRepository(db *gorm.DB) Repository {
	return NewRepository(db)
}

func ProvideService(repo Repository, logger2 *zap.Logger) *Service {
	return NewService(repo, logger2)
}

func ProvideHandler(service *Service, logger2 *zap.Logger) *Handler {
	return NewHandler(service, logger2)
}
