// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: form/v1/form.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SubmitFormRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SubmitFormRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubmitFormRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubmitFormRequestMultiError, or nil if none found.
func (m *SubmitFormRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SubmitFormRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	// no validation rules for StepId

	// no validation rules for UserId

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SubmitFormRequestValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SubmitFormRequestValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SubmitFormRequestValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SubmitFormRequestMultiError(errors)
	}

	return nil
}

// SubmitFormRequestMultiError is an error wrapping multiple validation errors
// returned by SubmitFormRequest.ValidateAll() if the designated constraints
// aren't met.
type SubmitFormRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubmitFormRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubmitFormRequestMultiError) AllErrors() []error { return m }

// SubmitFormRequestValidationError is the validation error returned by
// SubmitFormRequest.Validate if the designated constraints aren't met.
type SubmitFormRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubmitFormRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubmitFormRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubmitFormRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubmitFormRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubmitFormRequestValidationError) ErrorName() string {
	return "SubmitFormRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SubmitFormRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubmitFormRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubmitFormRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubmitFormRequestValidationError{}

// Validate checks the field values on SubmitFormResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SubmitFormResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubmitFormResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubmitFormResponseMultiError, or nil if none found.
func (m *SubmitFormResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SubmitFormResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SubmissionId

	// no validation rules for Success

	if len(errors) > 0 {
		return SubmitFormResponseMultiError(errors)
	}

	return nil
}

// SubmitFormResponseMultiError is an error wrapping multiple validation errors
// returned by SubmitFormResponse.ValidateAll() if the designated constraints
// aren't met.
type SubmitFormResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubmitFormResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubmitFormResponseMultiError) AllErrors() []error { return m }

// SubmitFormResponseValidationError is the validation error returned by
// SubmitFormResponse.Validate if the designated constraints aren't met.
type SubmitFormResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubmitFormResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubmitFormResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubmitFormResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubmitFormResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubmitFormResponseValidationError) ErrorName() string {
	return "SubmitFormResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SubmitFormResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubmitFormResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubmitFormResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubmitFormResponseValidationError{}

// Validate checks the field values on GetFormSubmissionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetFormSubmissionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetFormSubmissionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetFormSubmissionRequestMultiError, or nil if none found.
func (m *GetFormSubmissionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetFormSubmissionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SubmissionId

	if len(errors) > 0 {
		return GetFormSubmissionRequestMultiError(errors)
	}

	return nil
}

// GetFormSubmissionRequestMultiError is an error wrapping multiple validation
// errors returned by GetFormSubmissionRequest.ValidateAll() if the designated
// constraints aren't met.
type GetFormSubmissionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetFormSubmissionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetFormSubmissionRequestMultiError) AllErrors() []error { return m }

// GetFormSubmissionRequestValidationError is the validation error returned by
// GetFormSubmissionRequest.Validate if the designated constraints aren't met.
type GetFormSubmissionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFormSubmissionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFormSubmissionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFormSubmissionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFormSubmissionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFormSubmissionRequestValidationError) ErrorName() string {
	return "GetFormSubmissionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetFormSubmissionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFormSubmissionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFormSubmissionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFormSubmissionRequestValidationError{}

// Validate checks the field values on GetFormSubmissionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetFormSubmissionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetFormSubmissionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetFormSubmissionResponseMultiError, or nil if none found.
func (m *GetFormSubmissionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetFormSubmissionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SubmissionId

	// no validation rules for ProjectId

	// no validation rules for StepId

	// no validation rules for UserId

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetFormSubmissionResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetFormSubmissionResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetFormSubmissionResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetFormSubmissionResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetFormSubmissionResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetFormSubmissionResponseValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetFormSubmissionResponseMultiError(errors)
	}

	return nil
}

// GetFormSubmissionResponseMultiError is an error wrapping multiple validation
// errors returned by GetFormSubmissionResponse.ValidateAll() if the
// designated constraints aren't met.
type GetFormSubmissionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetFormSubmissionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetFormSubmissionResponseMultiError) AllErrors() []error { return m }

// GetFormSubmissionResponseValidationError is the validation error returned by
// GetFormSubmissionResponse.Validate if the designated constraints aren't met.
type GetFormSubmissionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetFormSubmissionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetFormSubmissionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetFormSubmissionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetFormSubmissionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetFormSubmissionResponseValidationError) ErrorName() string {
	return "GetFormSubmissionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetFormSubmissionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetFormSubmissionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetFormSubmissionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetFormSubmissionResponseValidationError{}

// Validate checks the field values on ListProjectFormsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListProjectFormsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListProjectFormsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListProjectFormsRequestMultiError, or nil if none found.
func (m *ListProjectFormsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListProjectFormsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	if len(errors) > 0 {
		return ListProjectFormsRequestMultiError(errors)
	}

	return nil
}

// ListProjectFormsRequestMultiError is an error wrapping multiple validation
// errors returned by ListProjectFormsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListProjectFormsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListProjectFormsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListProjectFormsRequestMultiError) AllErrors() []error { return m }

// ListProjectFormsRequestValidationError is the validation error returned by
// ListProjectFormsRequest.Validate if the designated constraints aren't met.
type ListProjectFormsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListProjectFormsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListProjectFormsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListProjectFormsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListProjectFormsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListProjectFormsRequestValidationError) ErrorName() string {
	return "ListProjectFormsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListProjectFormsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListProjectFormsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListProjectFormsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListProjectFormsRequestValidationError{}

// Validate checks the field values on FormPreview with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *FormPreview) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FormPreview with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FormPreviewMultiError, or
// nil if none found.
func (m *FormPreview) ValidateAll() error {
	return m.validate(true)
}

func (m *FormPreview) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SubmissionId

	// no validation rules for StepId

	// no validation rules for StepName

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FormPreviewValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FormPreviewValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FormPreviewValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return FormPreviewMultiError(errors)
	}

	return nil
}

// FormPreviewMultiError is an error wrapping multiple validation errors
// returned by FormPreview.ValidateAll() if the designated constraints aren't met.
type FormPreviewMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FormPreviewMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FormPreviewMultiError) AllErrors() []error { return m }

// FormPreviewValidationError is the validation error returned by
// FormPreview.Validate if the designated constraints aren't met.
type FormPreviewValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FormPreviewValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FormPreviewValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FormPreviewValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FormPreviewValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FormPreviewValidationError) ErrorName() string { return "FormPreviewValidationError" }

// Error satisfies the builtin error interface
func (e FormPreviewValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFormPreview.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FormPreviewValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FormPreviewValidationError{}

// Validate checks the field values on ListProjectFormsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListProjectFormsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListProjectFormsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListProjectFormsResponseMultiError, or nil if none found.
func (m *ListProjectFormsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListProjectFormsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetForms() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListProjectFormsResponseValidationError{
						field:  fmt.Sprintf("Forms[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListProjectFormsResponseValidationError{
						field:  fmt.Sprintf("Forms[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListProjectFormsResponseValidationError{
					field:  fmt.Sprintf("Forms[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListProjectFormsResponseMultiError(errors)
	}

	return nil
}

// ListProjectFormsResponseMultiError is an error wrapping multiple validation
// errors returned by ListProjectFormsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListProjectFormsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListProjectFormsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListProjectFormsResponseMultiError) AllErrors() []error { return m }

// ListProjectFormsResponseValidationError is the validation error returned by
// ListProjectFormsResponse.Validate if the designated constraints aren't met.
type ListProjectFormsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListProjectFormsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListProjectFormsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListProjectFormsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListProjectFormsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListProjectFormsResponseValidationError) ErrorName() string {
	return "ListProjectFormsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListProjectFormsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListProjectFormsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListProjectFormsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListProjectFormsResponseValidationError{}
