env: "local"
grpc_port: 8082
jwt:
  secret: ""
  access_token_ttl: 15m
  refresh_token_ttl: 720h
database:
  dsn: ""
services:
  university_addr: "university_service:8081"
allowed_origins:
  - "https://diplomaflow.kz"
  - "http://localhost:3000"
