// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: task/v1/task.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskService_GetBoard_FullMethodName             = "/task.v1.TaskService/GetBoard"
	TaskService_GetBoardByProject_FullMethodName    = "/task.v1.TaskService/GetBoardByProject"
	TaskService_ListMyBoards_FullMethodName         = "/task.v1.TaskService/ListMyBoards"
	TaskService_UpdateBoard_FullMethodName          = "/task.v1.TaskService/UpdateBoard"
	TaskService_ListColumns_FullMethodName          = "/task.v1.TaskService/ListColumns"
	TaskService_CreateColumn_FullMethodName         = "/task.v1.TaskService/CreateColumn"
	TaskService_UpdateColumn_FullMethodName         = "/task.v1.TaskService/UpdateColumn"
	TaskService_DeleteColumn_FullMethodName         = "/task.v1.TaskService/DeleteColumn"
	TaskService_ReorderColumns_FullMethodName       = "/task.v1.TaskService/ReorderColumns"
	TaskService_CreateTask_FullMethodName           = "/task.v1.TaskService/CreateTask"
	TaskService_GetTask_FullMethodName              = "/task.v1.TaskService/GetTask"
	TaskService_UpdateTask_FullMethodName           = "/task.v1.TaskService/UpdateTask"
	TaskService_DeleteTask_FullMethodName           = "/task.v1.TaskService/DeleteTask"
	TaskService_ListTasks_FullMethodName            = "/task.v1.TaskService/ListTasks"
	TaskService_MoveTask_FullMethodName             = "/task.v1.TaskService/MoveTask"
	TaskService_ReorderTasks_FullMethodName         = "/task.v1.TaskService/ReorderTasks"
	TaskService_BulkUpdateTasks_FullMethodName      = "/task.v1.TaskService/BulkUpdateTasks"
	TaskService_BulkDeleteTasks_FullMethodName      = "/task.v1.TaskService/BulkDeleteTasks"
	TaskService_AssignTask_FullMethodName           = "/task.v1.TaskService/AssignTask"
	TaskService_UnassignTask_FullMethodName         = "/task.v1.TaskService/UnassignTask"
	TaskService_CreateComment_FullMethodName        = "/task.v1.TaskService/CreateComment"
	TaskService_UpdateComment_FullMethodName        = "/task.v1.TaskService/UpdateComment"
	TaskService_DeleteComment_FullMethodName        = "/task.v1.TaskService/DeleteComment"
	TaskService_ListComments_FullMethodName         = "/task.v1.TaskService/ListComments"
	TaskService_AddAttachment_FullMethodName        = "/task.v1.TaskService/AddAttachment"
	TaskService_RemoveAttachment_FullMethodName     = "/task.v1.TaskService/RemoveAttachment"
	TaskService_ListAttachments_FullMethodName      = "/task.v1.TaskService/ListAttachments"
	TaskService_GetTaskActivity_FullMethodName      = "/task.v1.TaskService/GetTaskActivity"
	TaskService_AddWatcher_FullMethodName           = "/task.v1.TaskService/AddWatcher"
	TaskService_RemoveWatcher_FullMethodName        = "/task.v1.TaskService/RemoveWatcher"
	TaskService_ListWatchers_FullMethodName         = "/task.v1.TaskService/ListWatchers"
	TaskService_GetBoardStats_FullMethodName        = "/task.v1.TaskService/GetBoardStats"
	TaskService_GetMyTasks_FullMethodName           = "/task.v1.TaskService/GetMyTasks"
	TaskService_GetOverdueTasks_FullMethodName      = "/task.v1.TaskService/GetOverdueTasks"
	TaskService_GetUpcomingDeadlines_FullMethodName = "/task.v1.TaskService/GetUpcomingDeadlines"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== SERVICE ====================
type TaskServiceClient interface {
	// ==================== Board ====================
	GetBoard(ctx context.Context, in *GetBoardRequest, opts ...grpc.CallOption) (*GetBoardResponse, error)
	// project-first
	GetBoardByProject(ctx context.Context, in *GetBoardByProjectRequest, opts ...grpc.CallOption) (*GetBoardResponse, error)
	// list boards for different roles (student/teacher/admin)
	ListMyBoards(ctx context.Context, in *ListMyBoardsRequest, opts ...grpc.CallOption) (*ListMyBoardsResponse, error)
	UpdateBoard(ctx context.Context, in *UpdateBoardRequest, opts ...grpc.CallOption) (*Board, error)
	// ==================== Columns ====================
	ListColumns(ctx context.Context, in *ListColumnsRequest, opts ...grpc.CallOption) (*ListColumnsResponse, error)
	CreateColumn(ctx context.Context, in *CreateColumnRequest, opts ...grpc.CallOption) (*Column, error)
	UpdateColumn(ctx context.Context, in *UpdateColumnRequest, opts ...grpc.CallOption) (*Column, error)
	DeleteColumn(ctx context.Context, in *DeleteColumnRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReorderColumns(ctx context.Context, in *ReorderColumnsRequest, opts ...grpc.CallOption) (*ListColumnsResponse, error)
	// ==================== Tasks ====================
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*Task, error)
	DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	// Kanban операции
	MoveTask(ctx context.Context, in *MoveTaskRequest, opts ...grpc.CallOption) (*Task, error)
	ReorderTasks(ctx context.Context, in *ReorderTasksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Bulk операции
	BulkUpdateTasks(ctx context.Context, in *BulkUpdateTasksRequest, opts ...grpc.CallOption) (*BulkUpdateTasksResponse, error)
	BulkDeleteTasks(ctx context.Context, in *BulkDeleteTasksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ==================== Assignment ====================
	AssignTask(ctx context.Context, in *AssignTaskRequest, opts ...grpc.CallOption) (*Task, error)
	UnassignTask(ctx context.Context, in *UnassignTaskRequest, opts ...grpc.CallOption) (*Task, error)
	// ==================== Comments ====================
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*Comment, error)
	UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*Comment, error)
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
	// ==================== Attachments ====================
	AddAttachment(ctx context.Context, in *AddAttachmentRequest, opts ...grpc.CallOption) (*Attachment, error)
	RemoveAttachment(ctx context.Context, in *RemoveAttachmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListAttachments(ctx context.Context, in *ListAttachmentsRequest, opts ...grpc.CallOption) (*ListAttachmentsResponse, error)
	// ==================== Activity ====================
	GetTaskActivity(ctx context.Context, in *GetTaskActivityRequest, opts ...grpc.CallOption) (*GetTaskActivityResponse, error)
	// ==================== Watchers ====================
	AddWatcher(ctx context.Context, in *AddWatcherRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveWatcher(ctx context.Context, in *RemoveWatcherRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListWatchers(ctx context.Context, in *ListWatchersRequest, opts ...grpc.CallOption) (*ListWatchersResponse, error)
	// ==================== Dashboard & Stats ====================
	GetBoardStats(ctx context.Context, in *GetBoardStatsRequest, opts ...grpc.CallOption) (*GetBoardStatsResponse, error)
	GetMyTasks(ctx context.Context, in *GetMyTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	GetOverdueTasks(ctx context.Context, in *GetOverdueTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	GetUpcomingDeadlines(ctx context.Context, in *GetUpcomingDeadlinesRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) GetBoard(ctx context.Context, in *GetBoardRequest, opts ...grpc.CallOption) (*GetBoardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBoardResponse)
	err := c.cc.Invoke(ctx, TaskService_GetBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetBoardByProject(ctx context.Context, in *GetBoardByProjectRequest, opts ...grpc.CallOption) (*GetBoardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBoardResponse)
	err := c.cc.Invoke(ctx, TaskService_GetBoardByProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListMyBoards(ctx context.Context, in *ListMyBoardsRequest, opts ...grpc.CallOption) (*ListMyBoardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyBoardsResponse)
	err := c.cc.Invoke(ctx, TaskService_ListMyBoards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateBoard(ctx context.Context, in *UpdateBoardRequest, opts ...grpc.CallOption) (*Board, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Board)
	err := c.cc.Invoke(ctx, TaskService_UpdateBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListColumns(ctx context.Context, in *ListColumnsRequest, opts ...grpc.CallOption) (*ListColumnsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListColumnsResponse)
	err := c.cc.Invoke(ctx, TaskService_ListColumns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CreateColumn(ctx context.Context, in *CreateColumnRequest, opts ...grpc.CallOption) (*Column, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Column)
	err := c.cc.Invoke(ctx, TaskService_CreateColumn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateColumn(ctx context.Context, in *UpdateColumnRequest, opts ...grpc.CallOption) (*Column, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Column)
	err := c.cc.Invoke(ctx, TaskService_UpdateColumn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeleteColumn(ctx context.Context, in *DeleteColumnRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TaskService_DeleteColumn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ReorderColumns(ctx context.Context, in *ReorderColumnsRequest, opts ...grpc.CallOption) (*ListColumnsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListColumnsResponse)
	err := c.cc.Invoke(ctx, TaskService_ReorderColumns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, TaskService_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, TaskService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, TaskService_UpdateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TaskService_DeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, TaskService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) MoveTask(ctx context.Context, in *MoveTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, TaskService_MoveTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ReorderTasks(ctx context.Context, in *ReorderTasksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TaskService_ReorderTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) BulkUpdateTasks(ctx context.Context, in *BulkUpdateTasksRequest, opts ...grpc.CallOption) (*BulkUpdateTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkUpdateTasksResponse)
	err := c.cc.Invoke(ctx, TaskService_BulkUpdateTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) BulkDeleteTasks(ctx context.Context, in *BulkDeleteTasksRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TaskService_BulkDeleteTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) AssignTask(ctx context.Context, in *AssignTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, TaskService_AssignTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UnassignTask(ctx context.Context, in *UnassignTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, TaskService_UnassignTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Comment)
	err := c.cc.Invoke(ctx, TaskService_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Comment)
	err := c.cc.Invoke(ctx, TaskService_UpdateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TaskService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommentsResponse)
	err := c.cc.Invoke(ctx, TaskService_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) AddAttachment(ctx context.Context, in *AddAttachmentRequest, opts ...grpc.CallOption) (*Attachment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Attachment)
	err := c.cc.Invoke(ctx, TaskService_AddAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) RemoveAttachment(ctx context.Context, in *RemoveAttachmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TaskService_RemoveAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListAttachments(ctx context.Context, in *ListAttachmentsRequest, opts ...grpc.CallOption) (*ListAttachmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAttachmentsResponse)
	err := c.cc.Invoke(ctx, TaskService_ListAttachments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTaskActivity(ctx context.Context, in *GetTaskActivityRequest, opts ...grpc.CallOption) (*GetTaskActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskActivityResponse)
	err := c.cc.Invoke(ctx, TaskService_GetTaskActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) AddWatcher(ctx context.Context, in *AddWatcherRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TaskService_AddWatcher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) RemoveWatcher(ctx context.Context, in *RemoveWatcherRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TaskService_RemoveWatcher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListWatchers(ctx context.Context, in *ListWatchersRequest, opts ...grpc.CallOption) (*ListWatchersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWatchersResponse)
	err := c.cc.Invoke(ctx, TaskService_ListWatchers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetBoardStats(ctx context.Context, in *GetBoardStatsRequest, opts ...grpc.CallOption) (*GetBoardStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBoardStatsResponse)
	err := c.cc.Invoke(ctx, TaskService_GetBoardStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetMyTasks(ctx context.Context, in *GetMyTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, TaskService_GetMyTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetOverdueTasks(ctx context.Context, in *GetOverdueTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, TaskService_GetOverdueTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetUpcomingDeadlines(ctx context.Context, in *GetUpcomingDeadlinesRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, TaskService_GetUpcomingDeadlines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility.
//
// ==================== SERVICE ====================
type TaskServiceServer interface {
	// ==================== Board ====================
	GetBoard(context.Context, *GetBoardRequest) (*GetBoardResponse, error)
	// project-first
	GetBoardByProject(context.Context, *GetBoardByProjectRequest) (*GetBoardResponse, error)
	// list boards for different roles (student/teacher/admin)
	ListMyBoards(context.Context, *ListMyBoardsRequest) (*ListMyBoardsResponse, error)
	UpdateBoard(context.Context, *UpdateBoardRequest) (*Board, error)
	// ==================== Columns ====================
	ListColumns(context.Context, *ListColumnsRequest) (*ListColumnsResponse, error)
	CreateColumn(context.Context, *CreateColumnRequest) (*Column, error)
	UpdateColumn(context.Context, *UpdateColumnRequest) (*Column, error)
	DeleteColumn(context.Context, *DeleteColumnRequest) (*emptypb.Empty, error)
	ReorderColumns(context.Context, *ReorderColumnsRequest) (*ListColumnsResponse, error)
	// ==================== Tasks ====================
	CreateTask(context.Context, *CreateTaskRequest) (*Task, error)
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	UpdateTask(context.Context, *UpdateTaskRequest) (*Task, error)
	DeleteTask(context.Context, *DeleteTaskRequest) (*emptypb.Empty, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	// Kanban операции
	MoveTask(context.Context, *MoveTaskRequest) (*Task, error)
	ReorderTasks(context.Context, *ReorderTasksRequest) (*emptypb.Empty, error)
	// Bulk операции
	BulkUpdateTasks(context.Context, *BulkUpdateTasksRequest) (*BulkUpdateTasksResponse, error)
	BulkDeleteTasks(context.Context, *BulkDeleteTasksRequest) (*emptypb.Empty, error)
	// ==================== Assignment ====================
	AssignTask(context.Context, *AssignTaskRequest) (*Task, error)
	UnassignTask(context.Context, *UnassignTaskRequest) (*Task, error)
	// ==================== Comments ====================
	CreateComment(context.Context, *CreateCommentRequest) (*Comment, error)
	UpdateComment(context.Context, *UpdateCommentRequest) (*Comment, error)
	DeleteComment(context.Context, *DeleteCommentRequest) (*emptypb.Empty, error)
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error)
	// ==================== Attachments ====================
	AddAttachment(context.Context, *AddAttachmentRequest) (*Attachment, error)
	RemoveAttachment(context.Context, *RemoveAttachmentRequest) (*emptypb.Empty, error)
	ListAttachments(context.Context, *ListAttachmentsRequest) (*ListAttachmentsResponse, error)
	// ==================== Activity ====================
	GetTaskActivity(context.Context, *GetTaskActivityRequest) (*GetTaskActivityResponse, error)
	// ==================== Watchers ====================
	AddWatcher(context.Context, *AddWatcherRequest) (*emptypb.Empty, error)
	RemoveWatcher(context.Context, *RemoveWatcherRequest) (*emptypb.Empty, error)
	ListWatchers(context.Context, *ListWatchersRequest) (*ListWatchersResponse, error)
	// ==================== Dashboard & Stats ====================
	GetBoardStats(context.Context, *GetBoardStatsRequest) (*GetBoardStatsResponse, error)
	GetMyTasks(context.Context, *GetMyTasksRequest) (*ListTasksResponse, error)
	GetOverdueTasks(context.Context, *GetOverdueTasksRequest) (*ListTasksResponse, error)
	GetUpcomingDeadlines(context.Context, *GetUpcomingDeadlinesRequest) (*ListTasksResponse, error)
	mustEmbedUnimplementedTaskServiceServer()
}

// UnimplementedTaskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskServiceServer struct{}

func (UnimplementedTaskServiceServer) GetBoard(context.Context, *GetBoardRequest) (*GetBoardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBoard not implemented")
}
func (UnimplementedTaskServiceServer) GetBoardByProject(context.Context, *GetBoardByProjectRequest) (*GetBoardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBoardByProject not implemented")
}
func (UnimplementedTaskServiceServer) ListMyBoards(context.Context, *ListMyBoardsRequest) (*ListMyBoardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyBoards not implemented")
}
func (UnimplementedTaskServiceServer) UpdateBoard(context.Context, *UpdateBoardRequest) (*Board, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBoard not implemented")
}
func (UnimplementedTaskServiceServer) ListColumns(context.Context, *ListColumnsRequest) (*ListColumnsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListColumns not implemented")
}
func (UnimplementedTaskServiceServer) CreateColumn(context.Context, *CreateColumnRequest) (*Column, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateColumn not implemented")
}
func (UnimplementedTaskServiceServer) UpdateColumn(context.Context, *UpdateColumnRequest) (*Column, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateColumn not implemented")
}
func (UnimplementedTaskServiceServer) DeleteColumn(context.Context, *DeleteColumnRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteColumn not implemented")
}
func (UnimplementedTaskServiceServer) ReorderColumns(context.Context, *ReorderColumnsRequest) (*ListColumnsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReorderColumns not implemented")
}
func (UnimplementedTaskServiceServer) CreateTask(context.Context, *CreateTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedTaskServiceServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTaskServiceServer) UpdateTask(context.Context, *UpdateTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedTaskServiceServer) DeleteTask(context.Context, *DeleteTaskRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedTaskServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedTaskServiceServer) MoveTask(context.Context, *MoveTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveTask not implemented")
}
func (UnimplementedTaskServiceServer) ReorderTasks(context.Context, *ReorderTasksRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReorderTasks not implemented")
}
func (UnimplementedTaskServiceServer) BulkUpdateTasks(context.Context, *BulkUpdateTasksRequest) (*BulkUpdateTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkUpdateTasks not implemented")
}
func (UnimplementedTaskServiceServer) BulkDeleteTasks(context.Context, *BulkDeleteTasksRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkDeleteTasks not implemented")
}
func (UnimplementedTaskServiceServer) AssignTask(context.Context, *AssignTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignTask not implemented")
}
func (UnimplementedTaskServiceServer) UnassignTask(context.Context, *UnassignTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method UnassignTask not implemented")
}
func (UnimplementedTaskServiceServer) CreateComment(context.Context, *CreateCommentRequest) (*Comment, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedTaskServiceServer) UpdateComment(context.Context, *UpdateCommentRequest) (*Comment, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateComment not implemented")
}
func (UnimplementedTaskServiceServer) DeleteComment(context.Context, *DeleteCommentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedTaskServiceServer) ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedTaskServiceServer) AddAttachment(context.Context, *AddAttachmentRequest) (*Attachment, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAttachment not implemented")
}
func (UnimplementedTaskServiceServer) RemoveAttachment(context.Context, *RemoveAttachmentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAttachment not implemented")
}
func (UnimplementedTaskServiceServer) ListAttachments(context.Context, *ListAttachmentsRequest) (*ListAttachmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAttachments not implemented")
}
func (UnimplementedTaskServiceServer) GetTaskActivity(context.Context, *GetTaskActivityRequest) (*GetTaskActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskActivity not implemented")
}
func (UnimplementedTaskServiceServer) AddWatcher(context.Context, *AddWatcherRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddWatcher not implemented")
}
func (UnimplementedTaskServiceServer) RemoveWatcher(context.Context, *RemoveWatcherRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveWatcher not implemented")
}
func (UnimplementedTaskServiceServer) ListWatchers(context.Context, *ListWatchersRequest) (*ListWatchersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWatchers not implemented")
}
func (UnimplementedTaskServiceServer) GetBoardStats(context.Context, *GetBoardStatsRequest) (*GetBoardStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBoardStats not implemented")
}
func (UnimplementedTaskServiceServer) GetMyTasks(context.Context, *GetMyTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyTasks not implemented")
}
func (UnimplementedTaskServiceServer) GetOverdueTasks(context.Context, *GetOverdueTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOverdueTasks not implemented")
}
func (UnimplementedTaskServiceServer) GetUpcomingDeadlines(context.Context, *GetUpcomingDeadlinesRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUpcomingDeadlines not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}
func (UnimplementedTaskServiceServer) testEmbeddedByValue()                     {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_GetBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetBoard(ctx, req.(*GetBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetBoardByProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBoardByProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetBoardByProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetBoardByProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetBoardByProject(ctx, req.(*GetBoardByProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListMyBoards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyBoardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListMyBoards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListMyBoards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListMyBoards(ctx, req.(*ListMyBoardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UpdateBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UpdateBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_UpdateBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateBoard(ctx, req.(*UpdateBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListColumns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListColumnsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListColumns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListColumns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListColumns(ctx, req.(*ListColumnsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CreateColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateColumnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreateColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CreateColumn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreateColumn(ctx, req.(*CreateColumnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UpdateColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateColumnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UpdateColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_UpdateColumn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateColumn(ctx, req.(*UpdateColumnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeleteColumn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteColumnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeleteColumn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_DeleteColumn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeleteColumn(ctx, req.(*DeleteColumnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ReorderColumns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReorderColumnsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ReorderColumns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ReorderColumns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ReorderColumns(ctx, req.(*ReorderColumnsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_UpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeleteTask(ctx, req.(*DeleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_MoveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).MoveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_MoveTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).MoveTask(ctx, req.(*MoveTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ReorderTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReorderTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ReorderTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ReorderTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ReorderTasks(ctx, req.(*ReorderTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_BulkUpdateTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkUpdateTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).BulkUpdateTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_BulkUpdateTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).BulkUpdateTasks(ctx, req.(*BulkUpdateTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_BulkDeleteTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkDeleteTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).BulkDeleteTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_BulkDeleteTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).BulkDeleteTasks(ctx, req.(*BulkDeleteTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_AssignTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).AssignTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_AssignTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).AssignTask(ctx, req.(*AssignTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UnassignTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnassignTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UnassignTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_UnassignTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UnassignTask(ctx, req.(*UnassignTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_UpdateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateComment(ctx, req.(*UpdateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListComments(ctx, req.(*ListCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_AddAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).AddAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_AddAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).AddAttachment(ctx, req.(*AddAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_RemoveAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).RemoveAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_RemoveAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).RemoveAttachment(ctx, req.(*RemoveAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListAttachments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAttachmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListAttachments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListAttachments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListAttachments(ctx, req.(*ListAttachmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTaskActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTaskActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTaskActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTaskActivity(ctx, req.(*GetTaskActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_AddWatcher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWatcherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).AddWatcher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_AddWatcher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).AddWatcher(ctx, req.(*AddWatcherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_RemoveWatcher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWatcherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).RemoveWatcher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_RemoveWatcher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).RemoveWatcher(ctx, req.(*RemoveWatcherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListWatchers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWatchersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListWatchers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListWatchers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListWatchers(ctx, req.(*ListWatchersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetBoardStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBoardStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetBoardStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetBoardStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetBoardStats(ctx, req.(*GetBoardStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetMyTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetMyTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetMyTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetMyTasks(ctx, req.(*GetMyTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetOverdueTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOverdueTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetOverdueTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetOverdueTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetOverdueTasks(ctx, req.(*GetOverdueTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetUpcomingDeadlines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUpcomingDeadlinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetUpcomingDeadlines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetUpcomingDeadlines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetUpcomingDeadlines(ctx, req.(*GetUpcomingDeadlinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "task.v1.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBoard",
			Handler:    _TaskService_GetBoard_Handler,
		},
		{
			MethodName: "GetBoardByProject",
			Handler:    _TaskService_GetBoardByProject_Handler,
		},
		{
			MethodName: "ListMyBoards",
			Handler:    _TaskService_ListMyBoards_Handler,
		},
		{
			MethodName: "UpdateBoard",
			Handler:    _TaskService_UpdateBoard_Handler,
		},
		{
			MethodName: "ListColumns",
			Handler:    _TaskService_ListColumns_Handler,
		},
		{
			MethodName: "CreateColumn",
			Handler:    _TaskService_CreateColumn_Handler,
		},
		{
			MethodName: "UpdateColumn",
			Handler:    _TaskService_UpdateColumn_Handler,
		},
		{
			MethodName: "DeleteColumn",
			Handler:    _TaskService_DeleteColumn_Handler,
		},
		{
			MethodName: "ReorderColumns",
			Handler:    _TaskService_ReorderColumns_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _TaskService_CreateTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TaskService_GetTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _TaskService_UpdateTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _TaskService_DeleteTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _TaskService_ListTasks_Handler,
		},
		{
			MethodName: "MoveTask",
			Handler:    _TaskService_MoveTask_Handler,
		},
		{
			MethodName: "ReorderTasks",
			Handler:    _TaskService_ReorderTasks_Handler,
		},
		{
			MethodName: "BulkUpdateTasks",
			Handler:    _TaskService_BulkUpdateTasks_Handler,
		},
		{
			MethodName: "BulkDeleteTasks",
			Handler:    _TaskService_BulkDeleteTasks_Handler,
		},
		{
			MethodName: "AssignTask",
			Handler:    _TaskService_AssignTask_Handler,
		},
		{
			MethodName: "UnassignTask",
			Handler:    _TaskService_UnassignTask_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _TaskService_CreateComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _TaskService_UpdateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _TaskService_DeleteComment_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _TaskService_ListComments_Handler,
		},
		{
			MethodName: "AddAttachment",
			Handler:    _TaskService_AddAttachment_Handler,
		},
		{
			MethodName: "RemoveAttachment",
			Handler:    _TaskService_RemoveAttachment_Handler,
		},
		{
			MethodName: "ListAttachments",
			Handler:    _TaskService_ListAttachments_Handler,
		},
		{
			MethodName: "GetTaskActivity",
			Handler:    _TaskService_GetTaskActivity_Handler,
		},
		{
			MethodName: "AddWatcher",
			Handler:    _TaskService_AddWatcher_Handler,
		},
		{
			MethodName: "RemoveWatcher",
			Handler:    _TaskService_RemoveWatcher_Handler,
		},
		{
			MethodName: "ListWatchers",
			Handler:    _TaskService_ListWatchers_Handler,
		},
		{
			MethodName: "GetBoardStats",
			Handler:    _TaskService_GetBoardStats_Handler,
		},
		{
			MethodName: "GetMyTasks",
			Handler:    _TaskService_GetMyTasks_Handler,
		},
		{
			MethodName: "GetOverdueTasks",
			Handler:    _TaskService_GetOverdueTasks_Handler,
		},
		{
			MethodName: "GetUpcomingDeadlines",
			Handler:    _TaskService_GetUpcomingDeadlines_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task/v1/task.proto",
}
