syntax = "proto3";

package project;

option go_package = "pkg/protobuf/project";

service ProjectService{
  rpc CreateProject(CreateProjectRequest)
      returns (CreateProjectResponse);

  rpc GetProject(GetProjectRequest)
      returns (GetProjectResponse);

  rpc ListProjects(ListProjectsRequest)
      returns (ListProjectsResponse);

  rpc UpdateProject(UpdateProjectRequest)
      returns (UpdateProjectResponse);

  rpc DeleteProject(DeleteProjectRequest)
      returns (DeleteProjectResponse);

}

message CreateProjectRequest{
  string topic = 1;
  int64 supervisor_id = 2;
  repeated int64 student_ids = 3;
  int64 department_id = 4;
}
message CreateProjectResponse{
  int64 project_id = 1;
}

message GetProjectRequest{
  int64 project_id = 1;
}
message GetProjectResponse{
  Project project = 1;
}
message ListProjectsRequest{}
message ListProjectsResponse{
  repeated Project projects = 1;
}

message UpdateProjectRequest{
  int64 project_id = 1;
  string topic = 2;
}
message UpdateProjectResponse{
  Project project = 1;
}
message DeleteProjectRequest{
  int64 project_id = 1;
}
message DeleteProjectResponse{
  bool success = 1;
}

message Project{
  int64 id =1;
  string topic=2;
  int64 supervisor_id=3;
  int64 department_id=4;
  repeated int64 student_ids=5;
}