syntax = "proto3";

package project.v1;

import "google/protobuf/struct.proto";
import "google/protobuf/empty.proto";

option go_package = "github.com/lucky720s/diplomaflow/pkg/protobuf/project/v1";

message Project {
  int64 id = 1;
  string title = 2;
  int64 workflow_id = 3;
  int64 current_state_id = 4;
  string status = 5;
}

service ProjectService {
  rpc CreateProject(CreateProjectRequest) returns (Project);
  rpc GetProject(GetProjectRequest) returns (Project);
  rpc ListProjects(ListProjectsRequest) returns (ListProjectsResponse);
  rpc PerformStateAction(PerformStateActionRequest) returns (google.protobuf.Empty);
}

message CreateProjectRequest {
  string title = 1;
  int64 workflow_id = 2;
}

message GetProjectRequest {
  int64 project_id = 1;
}

message PerformStateActionRequest {
  int64 project_id = 1;
  string action = 2;
  google.protobuf.Struct payload = 3;
}
message ListProjectsRequest {
  int64 department_id = 1;
}

message ListProjectsResponse {
  repeated Project projects = 1;
}