// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package project

import (
	"github.com/lucky720s/diplomaflow/pkg/broker"
	"github.com/lucky720s/diplomaflow/pkg/protobuf/workflow/v1"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(cfg *Config, db *gorm.DB, log *zap.Logger, kafkaProducer *broker.Producer, wfClient v1.WorkflowServiceClient) (*App, func(), error) {
	projectRepository := NewRepository(db)
	workflowClient := ProvideWorkflowClient(wfClient)
	service := NewService(projectRepository, workflowClient, log)
	handler := NewHandler(service)
	deadlineScheduler := NewDeadlineScheduler(projectRepository, log)
	outboxProcessor := NewOutboxProcessor(projectRepository, kafkaProducer, log)
	app := NewApp(handler, deadlineScheduler, outboxProcessor)
	return app, func() {
	}, nil
}

// wire.go:

func ProvideWorkflowClient(c v1.WorkflowServiceClient) WorkflowClient {
	return c
}
