// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package project

import (
	"context"
	"github.com/lucky720s/diplomaflow/pkg/broker"
	"github.com/lucky720s/diplomaflow/pkg/protobuf/workflow/v1"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(cfg *Config, db *gorm.DB, log *zap.Logger, kafkaProducer *broker.Producer, wfClient v1.WorkflowServiceClient) (*App, func(), error) {
	projectRepository := NewRepository(db)
	workflowClient := ProvideWorkflowClient(wfClient)
	service := NewService(projectRepository, workflowClient, log)
	handler := NewHandler(service)
	deadlineScheduler := NewDeadlineScheduler(projectRepository, log)
	outboxProcessor := NewOutboxProcessor(projectRepository, kafkaProducer, log)
	app := NewApp(handler, deadlineScheduler, outboxProcessor)
	return app, func() {
	}, nil
}

// wire.go:

func ProvideWorkflowClient(c v1.WorkflowServiceClient) WorkflowClient {

	return &workflowClientWrapper{c: c}
}

// wrapper converts ...grpc.CallOption to ...interface{} usage (we ignore opts)
type workflowClientWrapper struct {
	c v1.WorkflowServiceClient
}

func (w *workflowClientWrapper) GetActiveWorkflowByDepartment(ctx context.Context, in *v1.GetActiveWorkflowByDepartmentRequest, _ ...interface{}) (*v1.Workflow, error) {
	return w.c.GetActiveWorkflowByDepartment(ctx, in)
}

func (w *workflowClientWrapper) GetAvailableTransitions(ctx context.Context, in *v1.GetAvailableTransitionsRequest, _ ...interface{}) (*v1.GetAvailableTransitionsResponse, error) {
	return w.c.GetAvailableTransitions(ctx, in)
}

func (w *workflowClientWrapper) ExecuteTransition(ctx context.Context, in *v1.ExecuteTransitionRequest, _ ...interface{}) (*v1.ExecuteTransitionResponse, error) {
	return w.c.ExecuteTransition(ctx, in)
}
