// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/protobuf/tenant/tenant.proto

package tenant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWorkflowTemplateIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  int64                  `protobuf:"varint,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowTemplateIDRequest) Reset() {
	*x = GetWorkflowTemplateIDRequest{}
	mi := &file_pkg_protobuf_tenant_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowTemplateIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowTemplateIDRequest) ProtoMessage() {}

func (x *GetWorkflowTemplateIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_tenant_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowTemplateIDRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowTemplateIDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_tenant_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *GetWorkflowTemplateIDRequest) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

type GetWorkflowTemplateIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    int64                  `protobuf:"varint,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowTemplateIDResponse) Reset() {
	*x = GetWorkflowTemplateIDResponse{}
	mi := &file_pkg_protobuf_tenant_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowTemplateIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowTemplateIDResponse) ProtoMessage() {}

func (x *GetWorkflowTemplateIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_tenant_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowTemplateIDResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowTemplateIDResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_tenant_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *GetWorkflowTemplateIDResponse) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

var File_pkg_protobuf_tenant_tenant_proto protoreflect.FileDescriptor

const file_pkg_protobuf_tenant_tenant_proto_rawDesc = "" +
	"\n" +
	" pkg/protobuf/tenant/tenant.proto\x12\x06tenant\"C\n" +
	"\x1cGetWorkflowTemplateIDRequest\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\x03R\fdepartmentId\"@\n" +
	"\x1dGetWorkflowTemplateIDResponse\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\x03R\n" +
	"templateId2u\n" +
	"\rTenantService\x12d\n" +
	"\x15GetWorkflowTemplateID\x12$.tenant.GetWorkflowTemplateIDRequest\x1a%.tenant.GetWorkflowTemplateIDResponseB\x15Z\x13pkg/protobuf/tenantb\x06proto3"

var (
	file_pkg_protobuf_tenant_tenant_proto_rawDescOnce sync.Once
	file_pkg_protobuf_tenant_tenant_proto_rawDescData []byte
)

func file_pkg_protobuf_tenant_tenant_proto_rawDescGZIP() []byte {
	file_pkg_protobuf_tenant_tenant_proto_rawDescOnce.Do(func() {
		file_pkg_protobuf_tenant_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protobuf_tenant_tenant_proto_rawDesc), len(file_pkg_protobuf_tenant_tenant_proto_rawDesc)))
	})
	return file_pkg_protobuf_tenant_tenant_proto_rawDescData
}

var file_pkg_protobuf_tenant_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_protobuf_tenant_tenant_proto_goTypes = []any{
	(*GetWorkflowTemplateIDRequest)(nil),  // 0: tenant.GetWorkflowTemplateIDRequest
	(*GetWorkflowTemplateIDResponse)(nil), // 1: tenant.GetWorkflowTemplateIDResponse
}
var file_pkg_protobuf_tenant_tenant_proto_depIdxs = []int32{
	0, // 0: tenant.TenantService.GetWorkflowTemplateID:input_type -> tenant.GetWorkflowTemplateIDRequest
	1, // 1: tenant.TenantService.GetWorkflowTemplateID:output_type -> tenant.GetWorkflowTemplateIDResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_protobuf_tenant_tenant_proto_init() }
func file_pkg_protobuf_tenant_tenant_proto_init() {
	if File_pkg_protobuf_tenant_tenant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protobuf_tenant_tenant_proto_rawDesc), len(file_pkg_protobuf_tenant_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protobuf_tenant_tenant_proto_goTypes,
		DependencyIndexes: file_pkg_protobuf_tenant_tenant_proto_depIdxs,
		MessageInfos:      file_pkg_protobuf_tenant_tenant_proto_msgTypes,
	}.Build()
	File_pkg_protobuf_tenant_tenant_proto = out.File
	file_pkg_protobuf_tenant_tenant_proto_goTypes = nil
	file_pkg_protobuf_tenant_tenant_proto_depIdxs = nil
}
