env: "local"
grpc_port: 8083
database:
  dsn: ""
kafka:
  enabled: false  # <-- переключатель, если надо включить кафку
  brokers: "kafka:29092"
services:
  workflow_addr: "workflow_service:8085"
  notification_addr: "notification_service:8087"