syntax = "proto3";

package team;

option go_package = "github.com/lucky720s/diplomaflow/pkg/protobuf/team/v1";

service TeamService {
  rpc CreateTeam (CreateTeamRequest) returns (CreateTeamResponse);
  rpc GetTeam (GetTeamRequest) returns (GetTeamResponse);
  rpc GetAvailableStudents (GetAvailableStudentsRequest) returns (GetAvailableStudentsResponse);
}

message CreateTeamRequest {
  string name = 1;
  int64 project_id = 2;
  repeated int64 member_ids = 3;
}

message CreateTeamResponse {
  int64 team_id = 1;
}

message GetTeamRequest {
  int64 team_id = 1;
}

message TeamMember {
  int64 user_id = 1;
  string role = 2;
}

message GetTeamResponse {
  int64 team_id = 1;
  string name = 2;
  int64 project_id = 3;
  repeated TeamMember members = 4;
}

message GetAvailableStudentsRequest {
  int64 university_id = 1;
}

message StudentPreview {
  int64 id = 1;
  string full_name = 2;
  string email = 3;
}

message GetAvailableStudentsResponse {
  repeated StudentPreview students = 1;
}
