services:
  main_postgres:
    image: postgres:18-alpine
    container_name: main_postgres
    environment:
      POSTGRES_USER: diplomaflow
      POSTGRES_PASSWORD: diplomaflow_pass
      POSTGRES_DB: diplomaflow
    ports:
      - "5432:5432"
    volumes:
      - diplomaflow_data:/var/lib/postgresql/data
      - ./init_schemas.sql:/docker-entrypoint-initdb.d/init_schemas.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U diplomaflow -d diplomaflow" ]
      interval: 5s
      timeout: 5s
      retries: 5
  university_service:
    build:
      context: ../../
      dockerfile: cmd/university_service/Dockerfile
    container_name: university_service
    env_file: .env
    ports:
      - "8081:8081"
    depends_on:
      main_postgres:
        condition: service_healthy

  role_service:
    build:
      context: ../../
      dockerfile: cmd/role_service/Dockerfile
    container_name: role_service
    env_file: .env
    ports:
      - "8086:8086"
    depends_on:
      main_postgres:
        condition: service_healthy

  auth_service:
    build:
      context: ../../
      dockerfile: cmd/auth_service/Dockerfile
    container_name: auth_service
    env_file: .env
    ports:
      - "8082:8082"
    depends_on:
      main_postgres:
        condition: service_healthy
      role_service:
        condition: service_started

  team_service:
    build:
      context: ../../
      dockerfile: cmd/team_service/Dockerfile
    container_name: team_service
    env_file: .env
    ports:
      - "8084:8084"
    depends_on:
      main_postgres:
        condition: service_healthy

  workflow_service:
    build:
      context: ../../
      dockerfile: cmd/workflow_service/Dockerfile
    container_name: workflow_service
    env_file: .env
    ports:
      - "8085:8085"
    depends_on:
      main_postgres:
        condition: service_healthy
  project_service:
    build:
      context: ../../
      dockerfile: cmd/project_service/Dockerfile
    container_name: project_service
    env_file: .env
    ports:
      - "8083:8083"
    depends_on:
      main_postgres:
        condition: service_healthy
      auth_service:
        condition: service_started
  api_gateway:
    build:
      context: ../../
      dockerfile: cmd/api_gateway/Dockerfile
    container_name: api_gateway
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      auth_service:
        condition: service_started
      project_service:
        condition: service_started
      role_service:
        condition: service_started
      team_service:
        condition: service_started
      workflow_service:
        condition: service_started

volumes:
  diplomaflow_data:


