CREATE SCHEMA IF NOT EXISTS auth_schema;
CREATE SCHEMA IF NOT EXISTS project_schema;
CREATE SCHEMA IF NOT EXISTS team_schema;
CREATE SCHEMA IF NOT EXISTS workflow_schema;
CREATE SCHEMA IF NOT EXISTS role_schema;
CREATE SCHEMA IF NOT EXISTS university_schema;
