env: "local"
port: 8080
jwt_secret: ""
services_auth_addr: "auth_service:8082"
services_project_addr: "project_service:8083"
services_team_addr: "team_service:8084"
services_task_addr: "task_service:8091"
services_university_addr: "university_service:8081"
services_role_addr: "role_service:8086"
services_workflow_addr: "workflow_service:8085"
services_notification_addr: "notification_service:8087"
services_file_addr: "file_service:8088"
services_form_addr: "form_service:8089"
services_admin_addr: "admin_service:8090"
redis_addr: "redis:6379"
allowed_origins:
  - "https://diplomaflow.kz"
  - "http://localhost:3000"
  - "http://localhost:5173"
