// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: team/v1/team.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MemberIds     []int64                `protobuf:"varint,2,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	LeaderId      int64                  `protobuf:"varint,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamRequest) Reset() {
	*x = CreateTeamRequest{}
	mi := &file_team_v1_team_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamRequest) ProtoMessage() {}

func (x *CreateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamRequest.ProtoReflect.Descriptor instead.
func (*CreateTeamRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTeamRequest) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *CreateTeamRequest) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

type CreateTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeamResponse) Reset() {
	*x = CreateTeamResponse{}
	mi := &file_team_v1_team_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeamResponse) ProtoMessage() {}

func (x *CreateTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeamResponse.ProtoReflect.Descriptor instead.
func (*CreateTeamResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTeamResponse) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

type GetTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamRequest) Reset() {
	*x = GetTeamRequest{}
	mi := &file_team_v1_team_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamRequest) ProtoMessage() {}

func (x *GetTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamRequest.ProtoReflect.Descriptor instead.
func (*GetTeamRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{2}
}

func (x *GetTeamRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

type TeamMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamMember) Reset() {
	*x = TeamMember{}
	mi := &file_team_v1_team_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamMember) ProtoMessage() {}

func (x *TeamMember) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamMember.ProtoReflect.Descriptor instead.
func (*TeamMember) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{3}
}

func (x *TeamMember) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TeamMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TeamMember) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *TeamMember) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *TeamMember) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Members       []*TeamMember          `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeamResponse) Reset() {
	*x = GetTeamResponse{}
	mi := &file_team_v1_team_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamResponse) ProtoMessage() {}

func (x *GetTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamResponse.ProtoReflect.Descriptor instead.
func (*GetTeamResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{4}
}

func (x *GetTeamResponse) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *GetTeamResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTeamResponse) GetMembers() []*TeamMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type GetAvailableStudentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UniversityId  int64                  `protobuf:"varint,1,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	DepartmentId  int64                  `protobuf:"varint,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	ExcludeUserId int64                  `protobuf:"varint,3,opt,name=exclude_user_id,json=excludeUserId,proto3" json:"exclude_user_id,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableStudentsRequest) Reset() {
	*x = GetAvailableStudentsRequest{}
	mi := &file_team_v1_team_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableStudentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableStudentsRequest) ProtoMessage() {}

func (x *GetAvailableStudentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableStudentsRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableStudentsRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{5}
}

func (x *GetAvailableStudentsRequest) GetUniversityId() int64 {
	if x != nil {
		return x.UniversityId
	}
	return 0
}

func (x *GetAvailableStudentsRequest) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *GetAvailableStudentsRequest) GetExcludeUserId() int64 {
	if x != nil {
		return x.ExcludeUserId
	}
	return 0
}

func (x *GetAvailableStudentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAvailableStudentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type StudentPreview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentPreview) Reset() {
	*x = StudentPreview{}
	mi := &file_team_v1_team_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentPreview) ProtoMessage() {}

func (x *StudentPreview) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentPreview.ProtoReflect.Descriptor instead.
func (*StudentPreview) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{6}
}

func (x *StudentPreview) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StudentPreview) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *StudentPreview) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetAvailableStudentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*StudentPreview      `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableStudentsResponse) Reset() {
	*x = GetAvailableStudentsResponse{}
	mi := &file_team_v1_team_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableStudentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableStudentsResponse) ProtoMessage() {}

func (x *GetAvailableStudentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableStudentsResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableStudentsResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{7}
}

func (x *GetAvailableStudentsResponse) GetStudents() []*StudentPreview {
	if x != nil {
		return x.Students
	}
	return nil
}

type Invite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId        int64                  `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TeamName      string                 `protobuf:"bytes,3,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	InviterId     int64                  `protobuf:"varint,4,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invite) Reset() {
	*x = Invite{}
	mi := &file_team_v1_team_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invite) ProtoMessage() {}

func (x *Invite) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invite.ProtoReflect.Descriptor instead.
func (*Invite) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{8}
}

func (x *Invite) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Invite) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *Invite) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *Invite) GetInviterId() int64 {
	if x != nil {
		return x.InviterId
	}
	return 0
}

func (x *Invite) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetMyInvitesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyInvitesRequest) Reset() {
	*x = GetMyInvitesRequest{}
	mi := &file_team_v1_team_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyInvitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyInvitesRequest) ProtoMessage() {}

func (x *GetMyInvitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyInvitesRequest.ProtoReflect.Descriptor instead.
func (*GetMyInvitesRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{9}
}

func (x *GetMyInvitesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetMyInvitesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invites       []*Invite              `protobuf:"bytes,1,rep,name=invites,proto3" json:"invites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyInvitesResponse) Reset() {
	*x = GetMyInvitesResponse{}
	mi := &file_team_v1_team_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyInvitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyInvitesResponse) ProtoMessage() {}

func (x *GetMyInvitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyInvitesResponse.ProtoReflect.Descriptor instead.
func (*GetMyInvitesResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{10}
}

func (x *GetMyInvitesResponse) GetInvites() []*Invite {
	if x != nil {
		return x.Invites
	}
	return nil
}

type RespondToInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteId      int64                  `protobuf:"varint,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Accept        bool                   `protobuf:"varint,3,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondToInviteRequest) Reset() {
	*x = RespondToInviteRequest{}
	mi := &file_team_v1_team_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondToInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToInviteRequest) ProtoMessage() {}

func (x *RespondToInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToInviteRequest.ProtoReflect.Descriptor instead.
func (*RespondToInviteRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{11}
}

func (x *RespondToInviteRequest) GetInviteId() int64 {
	if x != nil {
		return x.InviteId
	}
	return 0
}

func (x *RespondToInviteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RespondToInviteRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type RespondToInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondToInviteResponse) Reset() {
	*x = RespondToInviteResponse{}
	mi := &file_team_v1_team_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondToInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToInviteResponse) ProtoMessage() {}

func (x *RespondToInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToInviteResponse.ProtoReflect.Descriptor instead.
func (*RespondToInviteResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{12}
}

func (x *RespondToInviteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RespondToInviteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMyTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyTeamRequest) Reset() {
	*x = GetMyTeamRequest{}
	mi := &file_team_v1_team_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyTeamRequest) ProtoMessage() {}

func (x *GetMyTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyTeamRequest.ProtoReflect.Descriptor instead.
func (*GetMyTeamRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{13}
}

func (x *GetMyTeamRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetMyTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasTeam       bool                   `protobuf:"varint,1,opt,name=has_team,json=hasTeam,proto3" json:"has_team,omitempty"`
	Team          *TeamInfo              `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyTeamResponse) Reset() {
	*x = GetMyTeamResponse{}
	mi := &file_team_v1_team_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyTeamResponse) ProtoMessage() {}

func (x *GetMyTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyTeamResponse.ProtoReflect.Descriptor instead.
func (*GetMyTeamResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{14}
}

func (x *GetMyTeamResponse) GetHasTeam() bool {
	if x != nil {
		return x.HasTeam
	}
	return false
}

func (x *GetMyTeamResponse) GetTeam() *TeamInfo {
	if x != nil {
		return x.Team
	}
	return nil
}

type TeamInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TeamId              int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role                string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Members             []*TeamMember          `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`
	MemberCount         int32                  `protobuf:"varint,5,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	PendingInvitesCount int32                  `protobuf:"varint,6,opt,name=pending_invites_count,json=pendingInvitesCount,proto3" json:"pending_invites_count,omitempty"`
	InviteCode          string                 `protobuf:"bytes,7,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	CompositionLocked   bool                   `protobuf:"varint,8,opt,name=composition_locked,json=compositionLocked,proto3" json:"composition_locked,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TeamInfo) Reset() {
	*x = TeamInfo{}
	mi := &file_team_v1_team_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamInfo) ProtoMessage() {}

func (x *TeamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamInfo.ProtoReflect.Descriptor instead.
func (*TeamInfo) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{15}
}

func (x *TeamInfo) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *TeamInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TeamInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TeamInfo) GetMembers() []*TeamMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *TeamInfo) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *TeamInfo) GetPendingInvitesCount() int32 {
	if x != nil {
		return x.PendingInvitesCount
	}
	return 0
}

func (x *TeamInfo) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *TeamInfo) GetCompositionLocked() bool {
	if x != nil {
		return x.CompositionLocked
	}
	return false
}

type UpdateTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *Team                  `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	RequesterId   int64                  `protobuf:"varint,3,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamRequest) Reset() {
	*x = UpdateTeamRequest{}
	mi := &file_team_v1_team_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamRequest) ProtoMessage() {}

func (x *UpdateTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamRequest.ProtoReflect.Descriptor instead.
func (*UpdateTeamRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateTeamRequest) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

func (x *UpdateTeamRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateTeamRequest) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

type UpdateTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *Team                  `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeamResponse) Reset() {
	*x = UpdateTeamResponse{}
	mi := &file_team_v1_team_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeamResponse) ProtoMessage() {}

func (x *UpdateTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeamResponse.ProtoReflect.Descriptor instead.
func (*UpdateTeamResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateTeamResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

type DeleteTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	RequesterId   int64                  `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeamRequest) Reset() {
	*x = DeleteTeamRequest{}
	mi := &file_team_v1_team_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamRequest) ProtoMessage() {}

func (x *DeleteTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeamRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeamRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteTeamRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *DeleteTeamRequest) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_team_v1_team_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{19}
}

func (x *AddMemberRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *AddMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddMemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AddMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberResponse) Reset() {
	*x = AddMemberResponse{}
	mi := &file_team_v1_team_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberResponse) ProtoMessage() {}

func (x *AddMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberResponse.ProtoReflect.Descriptor instead.
func (*AddMemberResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{20}
}

func (x *AddMemberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddMemberResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequesterId   int64                  `protobuf:"varint,3,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_team_v1_team_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveMemberRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *RemoveMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveMemberRequest) GetRequesterId() int64 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

type Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Members       []*TeamMember          `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_team_v1_team_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{22}
}

func (x *Team) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Team) GetMembers() []*TeamMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Team) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListTeamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  int64                  `protobuf:"varint,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamsRequest) Reset() {
	*x = ListTeamsRequest{}
	mi := &file_team_v1_team_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsRequest) ProtoMessage() {}

func (x *ListTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsRequest.ProtoReflect.Descriptor instead.
func (*ListTeamsRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{23}
}

func (x *ListTeamsRequest) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *ListTeamsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTeamsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTeamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*Team                `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamsResponse) Reset() {
	*x = ListTeamsResponse{}
	mi := &file_team_v1_team_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsResponse) ProtoMessage() {}

func (x *ListTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsResponse.ProtoReflect.Descriptor instead.
func (*ListTeamsResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{24}
}

func (x *ListTeamsResponse) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *ListTeamsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type LeaveTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveTeamRequest) Reset() {
	*x = LeaveTeamRequest{}
	mi := &file_team_v1_team_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveTeamRequest) ProtoMessage() {}

func (x *LeaveTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveTeamRequest.ProtoReflect.Descriptor instead.
func (*LeaveTeamRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{25}
}

func (x *LeaveTeamRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *LeaveTeamRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LeaveTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TeamDeleted   bool                   `protobuf:"varint,3,opt,name=team_deleted,json=teamDeleted,proto3" json:"team_deleted,omitempty"`
	NewLeaderId   int64                  `protobuf:"varint,4,opt,name=new_leader_id,json=newLeaderId,proto3" json:"new_leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveTeamResponse) Reset() {
	*x = LeaveTeamResponse{}
	mi := &file_team_v1_team_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveTeamResponse) ProtoMessage() {}

func (x *LeaveTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveTeamResponse.ProtoReflect.Descriptor instead.
func (*LeaveTeamResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{26}
}

func (x *LeaveTeamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LeaveTeamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LeaveTeamResponse) GetTeamDeleted() bool {
	if x != nil {
		return x.TeamDeleted
	}
	return false
}

func (x *LeaveTeamResponse) GetNewLeaderId() int64 {
	if x != nil {
		return x.NewLeaderId
	}
	return 0
}

type TransferLeadershipRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TeamId          int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	CurrentLeaderId int64                  `protobuf:"varint,2,opt,name=current_leader_id,json=currentLeaderId,proto3" json:"current_leader_id,omitempty"`
	NewLeaderId     int64                  `protobuf:"varint,3,opt,name=new_leader_id,json=newLeaderId,proto3" json:"new_leader_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferLeadershipRequest) Reset() {
	*x = TransferLeadershipRequest{}
	mi := &file_team_v1_team_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferLeadershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferLeadershipRequest) ProtoMessage() {}

func (x *TransferLeadershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferLeadershipRequest.ProtoReflect.Descriptor instead.
func (*TransferLeadershipRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{27}
}

func (x *TransferLeadershipRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *TransferLeadershipRequest) GetCurrentLeaderId() int64 {
	if x != nil {
		return x.CurrentLeaderId
	}
	return 0
}

func (x *TransferLeadershipRequest) GetNewLeaderId() int64 {
	if x != nil {
		return x.NewLeaderId
	}
	return 0
}

type TransferLeadershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedTeam   *TeamInfo              `protobuf:"bytes,3,opt,name=updated_team,json=updatedTeam,proto3" json:"updated_team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferLeadershipResponse) Reset() {
	*x = TransferLeadershipResponse{}
	mi := &file_team_v1_team_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferLeadershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferLeadershipResponse) ProtoMessage() {}

func (x *TransferLeadershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferLeadershipResponse.ProtoReflect.Descriptor instead.
func (*TransferLeadershipResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{28}
}

func (x *TransferLeadershipResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferLeadershipResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransferLeadershipResponse) GetUpdatedTeam() *TeamInfo {
	if x != nil {
		return x.UpdatedTeam
	}
	return nil
}

type JoinTeamByCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteCode    string                 `protobuf:"bytes,1,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTeamByCodeRequest) Reset() {
	*x = JoinTeamByCodeRequest{}
	mi := &file_team_v1_team_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTeamByCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTeamByCodeRequest) ProtoMessage() {}

func (x *JoinTeamByCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTeamByCodeRequest.ProtoReflect.Descriptor instead.
func (*JoinTeamByCodeRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{29}
}

func (x *JoinTeamByCodeRequest) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

type JoinTeamByCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TeamId        int64                  `protobuf:"varint,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTeamByCodeResponse) Reset() {
	*x = JoinTeamByCodeResponse{}
	mi := &file_team_v1_team_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTeamByCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTeamByCodeResponse) ProtoMessage() {}

func (x *JoinTeamByCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTeamByCodeResponse.ProtoReflect.Descriptor instead.
func (*JoinTeamByCodeResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{30}
}

func (x *JoinTeamByCodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinTeamByCodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinTeamByCodeResponse) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

type RegenerateInviteCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateInviteCodeRequest) Reset() {
	*x = RegenerateInviteCodeRequest{}
	mi := &file_team_v1_team_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateInviteCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateInviteCodeRequest) ProtoMessage() {}

func (x *RegenerateInviteCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateInviteCodeRequest.ProtoReflect.Descriptor instead.
func (*RegenerateInviteCodeRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{31}
}

func (x *RegenerateInviteCodeRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

type RegenerateInviteCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteCode    string                 `protobuf:"bytes,1,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateInviteCodeResponse) Reset() {
	*x = RegenerateInviteCodeResponse{}
	mi := &file_team_v1_team_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateInviteCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateInviteCodeResponse) ProtoMessage() {}

func (x *RegenerateInviteCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateInviteCodeResponse.ProtoReflect.Descriptor instead.
func (*RegenerateInviteCodeResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{32}
}

func (x *RegenerateInviteCodeResponse) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

type LockTeamCompositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockTeamCompositionRequest) Reset() {
	*x = LockTeamCompositionRequest{}
	mi := &file_team_v1_team_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockTeamCompositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockTeamCompositionRequest) ProtoMessage() {}

func (x *LockTeamCompositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockTeamCompositionRequest.ProtoReflect.Descriptor instead.
func (*LockTeamCompositionRequest) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{33}
}

func (x *LockTeamCompositionRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *LockTeamCompositionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LockTeamCompositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockTeamCompositionResponse) Reset() {
	*x = LockTeamCompositionResponse{}
	mi := &file_team_v1_team_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockTeamCompositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockTeamCompositionResponse) ProtoMessage() {}

func (x *LockTeamCompositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_v1_team_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockTeamCompositionResponse.ProtoReflect.Descriptor instead.
func (*LockTeamCompositionResponse) Descriptor() ([]byte, []int) {
	return file_team_v1_team_proto_rawDescGZIP(), []int{34}
}

func (x *LockTeamCompositionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_team_v1_team_proto protoreflect.FileDescriptor

const file_team_v1_team_proto_rawDesc = "" +
	"\n" +
	"\x12team/v1/team.proto\x12\ateam.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x17validate/validate.proto\"c\n" +
	"\x11CreateTeamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x02 \x03(\x03R\tmemberIds\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\x03R\bleaderId\"-\n" +
	"\x12CreateTeamResponse\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\")\n" +
	"\x0eGetTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\"\x8b\x01\n" +
	"\n" +
	"TeamMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\"m\n" +
	"\x0fGetTeamResponse\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\amembers\x18\x03 \x03(\v2\x13.team.v1.TeamMemberR\amembers\"\xc0\x01\n" +
	"\x1bGetAvailableStudentsRequest\x12#\n" +
	"\runiversity_id\x18\x01 \x01(\x03R\funiversityId\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\x03R\fdepartmentId\x12&\n" +
	"\x0fexclude_user_id\x18\x03 \x01(\x03R\rexcludeUserId\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"S\n" +
	"\x0eStudentPreview\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"S\n" +
	"\x1cGetAvailableStudentsResponse\x123\n" +
	"\bstudents\x18\x01 \x03(\v2\x17.team.v1.StudentPreviewR\bstudents\"\x85\x01\n" +
	"\x06Invite\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x03R\x06teamId\x12\x1b\n" +
	"\tteam_name\x18\x03 \x01(\tR\bteamName\x12\x1d\n" +
	"\n" +
	"inviter_id\x18\x04 \x01(\x03R\tinviterId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\".\n" +
	"\x13GetMyInvitesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"A\n" +
	"\x14GetMyInvitesResponse\x12)\n" +
	"\ainvites\x18\x01 \x03(\v2\x0f.team.v1.InviteR\ainvites\"f\n" +
	"\x16RespondToInviteRequest\x12\x1b\n" +
	"\tinvite_id\x18\x01 \x01(\x03R\binviteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06accept\x18\x03 \x01(\bR\x06accept\"M\n" +
	"\x17RespondToInviteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"+\n" +
	"\x10GetMyTeamRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"U\n" +
	"\x11GetMyTeamResponse\x12\x19\n" +
	"\bhas_team\x18\x01 \x01(\bR\ahasTeam\x12%\n" +
	"\x04team\x18\x02 \x01(\v2\x11.team.v1.TeamInfoR\x04team\"\xa1\x02\n" +
	"\bTeamInfo\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12-\n" +
	"\amembers\x18\x04 \x03(\v2\x13.team.v1.TeamMemberR\amembers\x12!\n" +
	"\fmember_count\x18\x05 \x01(\x05R\vmemberCount\x122\n" +
	"\x15pending_invites_count\x18\x06 \x01(\x05R\x13pendingInvitesCount\x12\x1f\n" +
	"\vinvite_code\x18\a \x01(\tR\n" +
	"inviteCode\x12-\n" +
	"\x12composition_locked\x18\b \x01(\bR\x11compositionLocked\"\x96\x01\n" +
	"\x11UpdateTeamRequest\x12!\n" +
	"\x04team\x18\x01 \x01(\v2\r.team.v1.TeamR\x04team\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12!\n" +
	"\frequester_id\x18\x03 \x01(\x03R\vrequesterId\"7\n" +
	"\x12UpdateTeamResponse\x12!\n" +
	"\x04team\x18\x01 \x01(\v2\r.team.v1.TeamR\x04team\"O\n" +
	"\x11DeleteTeamRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\x03R\vrequesterId\"X\n" +
	"\x10AddMemberRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"G\n" +
	"\x11AddMemberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"j\n" +
	"\x13RemoveMemberRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\frequester_id\x18\x03 \x01(\x03R\vrequesterId\"x\n" +
	"\x04Team\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\amembers\x18\x03 \x03(\v2\x13.team.v1.TeamMemberR\amembers\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"h\n" +
	"\x10ListTeamsRequest\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\x03R\fdepartmentId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"Y\n" +
	"\x11ListTeamsResponse\x12#\n" +
	"\x05teams\x18\x01 \x03(\v2\r.team.v1.TeamR\x05teams\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"V\n" +
	"\x10LeaveTeamRequest\x12 \n" +
	"\ateam_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06teamId\x12 \n" +
	"\auser_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\"\x8e\x01\n" +
	"\x11LeaveTeamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fteam_deleted\x18\x03 \x01(\bR\vteamDeleted\x12\"\n" +
	"\rnew_leader_id\x18\x04 \x01(\x03R\vnewLeaderId\"\x9f\x01\n" +
	"\x19TransferLeadershipRequest\x12 \n" +
	"\ateam_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06teamId\x123\n" +
	"\x11current_leader_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x0fcurrentLeaderId\x12+\n" +
	"\rnew_leader_id\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\vnewLeaderId\"\x86\x01\n" +
	"\x1aTransferLeadershipResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\fupdated_team\x18\x03 \x01(\v2\x11.team.v1.TeamInfoR\vupdatedTeam\"C\n" +
	"\x15JoinTeamByCodeRequest\x12*\n" +
	"\vinvite_code\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x06\x18\x06R\n" +
	"inviteCode\"e\n" +
	"\x16JoinTeamByCodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\x03R\x06teamId\"?\n" +
	"\x1bRegenerateInviteCodeRequest\x12 \n" +
	"\ateam_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06teamId\"?\n" +
	"\x1cRegenerateInviteCodeResponse\x12\x1f\n" +
	"\vinvite_code\x18\x01 \x01(\tR\n" +
	"inviteCode\"V\n" +
	"\x1aLockTeamCompositionRequest\x12 \n" +
	"\ateam_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06teamId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"7\n" +
	"\x1bLockTeamCompositionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf2\t\n" +
	"\vTeamService\x12E\n" +
	"\n" +
	"CreateTeam\x12\x1a.team.v1.CreateTeamRequest\x1a\x1b.team.v1.CreateTeamResponse\x12<\n" +
	"\aGetTeam\x12\x17.team.v1.GetTeamRequest\x1a\x18.team.v1.GetTeamResponse\x12c\n" +
	"\x14GetAvailableStudents\x12$.team.v1.GetAvailableStudentsRequest\x1a%.team.v1.GetAvailableStudentsResponse\x12K\n" +
	"\fGetMyInvites\x12\x1c.team.v1.GetMyInvitesRequest\x1a\x1d.team.v1.GetMyInvitesResponse\x12T\n" +
	"\x0fRespondToInvite\x12\x1f.team.v1.RespondToInviteRequest\x1a .team.v1.RespondToInviteResponse\x12B\n" +
	"\tGetMyTeam\x12\x19.team.v1.GetMyTeamRequest\x1a\x1a.team.v1.GetMyTeamResponse\x12B\n" +
	"\tListTeams\x12\x19.team.v1.ListTeamsRequest\x1a\x1a.team.v1.ListTeamsResponse\x12E\n" +
	"\n" +
	"UpdateTeam\x12\x1a.team.v1.UpdateTeamRequest\x1a\x1b.team.v1.UpdateTeamResponse\x12@\n" +
	"\n" +
	"DeleteTeam\x12\x1a.team.v1.DeleteTeamRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\tAddMember\x12\x19.team.v1.AddMemberRequest\x1a\x1a.team.v1.AddMemberResponse\x12D\n" +
	"\fRemoveMember\x12\x1c.team.v1.RemoveMemberRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\tLeaveTeam\x12\x19.team.v1.LeaveTeamRequest\x1a\x1a.team.v1.LeaveTeamResponse\x12]\n" +
	"\x12TransferLeadership\x12\".team.v1.TransferLeadershipRequest\x1a#.team.v1.TransferLeadershipResponse\x12Q\n" +
	"\x0eJoinTeamByCode\x12\x1e.team.v1.JoinTeamByCodeRequest\x1a\x1f.team.v1.JoinTeamByCodeResponse\x12c\n" +
	"\x14RegenerateInviteCode\x12$.team.v1.RegenerateInviteCodeRequest\x1a%.team.v1.RegenerateInviteCodeResponse\x12`\n" +
	"\x13LockTeamComposition\x12#.team.v1.LockTeamCompositionRequest\x1a$.team.v1.LockTeamCompositionResponseB7Z5github.com/lucky720s/diplomaflow/pkg/protobuf/team/v1b\x06proto3"

var (
	file_team_v1_team_proto_rawDescOnce sync.Once
	file_team_v1_team_proto_rawDescData []byte
)

func file_team_v1_team_proto_rawDescGZIP() []byte {
	file_team_v1_team_proto_rawDescOnce.Do(func() {
		file_team_v1_team_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_team_v1_team_proto_rawDesc), len(file_team_v1_team_proto_rawDesc)))
	})
	return file_team_v1_team_proto_rawDescData
}

var file_team_v1_team_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_team_v1_team_proto_goTypes = []any{
	(*CreateTeamRequest)(nil),            // 0: team.v1.CreateTeamRequest
	(*CreateTeamResponse)(nil),           // 1: team.v1.CreateTeamResponse
	(*GetTeamRequest)(nil),               // 2: team.v1.GetTeamRequest
	(*TeamMember)(nil),                   // 3: team.v1.TeamMember
	(*GetTeamResponse)(nil),              // 4: team.v1.GetTeamResponse
	(*GetAvailableStudentsRequest)(nil),  // 5: team.v1.GetAvailableStudentsRequest
	(*StudentPreview)(nil),               // 6: team.v1.StudentPreview
	(*GetAvailableStudentsResponse)(nil), // 7: team.v1.GetAvailableStudentsResponse
	(*Invite)(nil),                       // 8: team.v1.Invite
	(*GetMyInvitesRequest)(nil),          // 9: team.v1.GetMyInvitesRequest
	(*GetMyInvitesResponse)(nil),         // 10: team.v1.GetMyInvitesResponse
	(*RespondToInviteRequest)(nil),       // 11: team.v1.RespondToInviteRequest
	(*RespondToInviteResponse)(nil),      // 12: team.v1.RespondToInviteResponse
	(*GetMyTeamRequest)(nil),             // 13: team.v1.GetMyTeamRequest
	(*GetMyTeamResponse)(nil),            // 14: team.v1.GetMyTeamResponse
	(*TeamInfo)(nil),                     // 15: team.v1.TeamInfo
	(*UpdateTeamRequest)(nil),            // 16: team.v1.UpdateTeamRequest
	(*UpdateTeamResponse)(nil),           // 17: team.v1.UpdateTeamResponse
	(*DeleteTeamRequest)(nil),            // 18: team.v1.DeleteTeamRequest
	(*AddMemberRequest)(nil),             // 19: team.v1.AddMemberRequest
	(*AddMemberResponse)(nil),            // 20: team.v1.AddMemberResponse
	(*RemoveMemberRequest)(nil),          // 21: team.v1.RemoveMemberRequest
	(*Team)(nil),                         // 22: team.v1.Team
	(*ListTeamsRequest)(nil),             // 23: team.v1.ListTeamsRequest
	(*ListTeamsResponse)(nil),            // 24: team.v1.ListTeamsResponse
	(*LeaveTeamRequest)(nil),             // 25: team.v1.LeaveTeamRequest
	(*LeaveTeamResponse)(nil),            // 26: team.v1.LeaveTeamResponse
	(*TransferLeadershipRequest)(nil),    // 27: team.v1.TransferLeadershipRequest
	(*TransferLeadershipResponse)(nil),   // 28: team.v1.TransferLeadershipResponse
	(*JoinTeamByCodeRequest)(nil),        // 29: team.v1.JoinTeamByCodeRequest
	(*JoinTeamByCodeResponse)(nil),       // 30: team.v1.JoinTeamByCodeResponse
	(*RegenerateInviteCodeRequest)(nil),  // 31: team.v1.RegenerateInviteCodeRequest
	(*RegenerateInviteCodeResponse)(nil), // 32: team.v1.RegenerateInviteCodeResponse
	(*LockTeamCompositionRequest)(nil),   // 33: team.v1.LockTeamCompositionRequest
	(*LockTeamCompositionResponse)(nil),  // 34: team.v1.LockTeamCompositionResponse
	(*fieldmaskpb.FieldMask)(nil),        // 35: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),                // 36: google.protobuf.Empty
}
var file_team_v1_team_proto_depIdxs = []int32{
	3,  // 0: team.v1.GetTeamResponse.members:type_name -> team.v1.TeamMember
	6,  // 1: team.v1.GetAvailableStudentsResponse.students:type_name -> team.v1.StudentPreview
	8,  // 2: team.v1.GetMyInvitesResponse.invites:type_name -> team.v1.Invite
	15, // 3: team.v1.GetMyTeamResponse.team:type_name -> team.v1.TeamInfo
	3,  // 4: team.v1.TeamInfo.members:type_name -> team.v1.TeamMember
	22, // 5: team.v1.UpdateTeamRequest.team:type_name -> team.v1.Team
	35, // 6: team.v1.UpdateTeamRequest.update_mask:type_name -> google.protobuf.FieldMask
	22, // 7: team.v1.UpdateTeamResponse.team:type_name -> team.v1.Team
	3,  // 8: team.v1.Team.members:type_name -> team.v1.TeamMember
	22, // 9: team.v1.ListTeamsResponse.teams:type_name -> team.v1.Team
	15, // 10: team.v1.TransferLeadershipResponse.updated_team:type_name -> team.v1.TeamInfo
	0,  // 11: team.v1.TeamService.CreateTeam:input_type -> team.v1.CreateTeamRequest
	2,  // 12: team.v1.TeamService.GetTeam:input_type -> team.v1.GetTeamRequest
	5,  // 13: team.v1.TeamService.GetAvailableStudents:input_type -> team.v1.GetAvailableStudentsRequest
	9,  // 14: team.v1.TeamService.GetMyInvites:input_type -> team.v1.GetMyInvitesRequest
	11, // 15: team.v1.TeamService.RespondToInvite:input_type -> team.v1.RespondToInviteRequest
	13, // 16: team.v1.TeamService.GetMyTeam:input_type -> team.v1.GetMyTeamRequest
	23, // 17: team.v1.TeamService.ListTeams:input_type -> team.v1.ListTeamsRequest
	16, // 18: team.v1.TeamService.UpdateTeam:input_type -> team.v1.UpdateTeamRequest
	18, // 19: team.v1.TeamService.DeleteTeam:input_type -> team.v1.DeleteTeamRequest
	19, // 20: team.v1.TeamService.AddMember:input_type -> team.v1.AddMemberRequest
	21, // 21: team.v1.TeamService.RemoveMember:input_type -> team.v1.RemoveMemberRequest
	25, // 22: team.v1.TeamService.LeaveTeam:input_type -> team.v1.LeaveTeamRequest
	27, // 23: team.v1.TeamService.TransferLeadership:input_type -> team.v1.TransferLeadershipRequest
	29, // 24: team.v1.TeamService.JoinTeamByCode:input_type -> team.v1.JoinTeamByCodeRequest
	31, // 25: team.v1.TeamService.RegenerateInviteCode:input_type -> team.v1.RegenerateInviteCodeRequest
	33, // 26: team.v1.TeamService.LockTeamComposition:input_type -> team.v1.LockTeamCompositionRequest
	1,  // 27: team.v1.TeamService.CreateTeam:output_type -> team.v1.CreateTeamResponse
	4,  // 28: team.v1.TeamService.GetTeam:output_type -> team.v1.GetTeamResponse
	7,  // 29: team.v1.TeamService.GetAvailableStudents:output_type -> team.v1.GetAvailableStudentsResponse
	10, // 30: team.v1.TeamService.GetMyInvites:output_type -> team.v1.GetMyInvitesResponse
	12, // 31: team.v1.TeamService.RespondToInvite:output_type -> team.v1.RespondToInviteResponse
	14, // 32: team.v1.TeamService.GetMyTeam:output_type -> team.v1.GetMyTeamResponse
	24, // 33: team.v1.TeamService.ListTeams:output_type -> team.v1.ListTeamsResponse
	17, // 34: team.v1.TeamService.UpdateTeam:output_type -> team.v1.UpdateTeamResponse
	36, // 35: team.v1.TeamService.DeleteTeam:output_type -> google.protobuf.Empty
	20, // 36: team.v1.TeamService.AddMember:output_type -> team.v1.AddMemberResponse
	36, // 37: team.v1.TeamService.RemoveMember:output_type -> google.protobuf.Empty
	26, // 38: team.v1.TeamService.LeaveTeam:output_type -> team.v1.LeaveTeamResponse
	28, // 39: team.v1.TeamService.TransferLeadership:output_type -> team.v1.TransferLeadershipResponse
	30, // 40: team.v1.TeamService.JoinTeamByCode:output_type -> team.v1.JoinTeamByCodeResponse
	32, // 41: team.v1.TeamService.RegenerateInviteCode:output_type -> team.v1.RegenerateInviteCodeResponse
	34, // 42: team.v1.TeamService.LockTeamComposition:output_type -> team.v1.LockTeamCompositionResponse
	27, // [27:43] is the sub-list for method output_type
	11, // [11:27] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_team_v1_team_proto_init() }
func file_team_v1_team_proto_init() {
	if File_team_v1_team_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_team_v1_team_proto_rawDesc), len(file_team_v1_team_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_team_v1_team_proto_goTypes,
		DependencyIndexes: file_team_v1_team_proto_depIdxs,
		MessageInfos:      file_team_v1_team_proto_msgTypes,
	}.Build()
	File_team_v1_team_proto = out.File
	file_team_v1_team_proto_goTypes = nil
	file_team_v1_team_proto_depIdxs = nil
}
