syntax = "proto3";

package auth;
import "validate/validate.proto";
option go_package = "github.com/lucky720s/diplomaflow/pkg/protobuf/auth/v1";

service AuthService {
  rpc Register (RegisterRequest) returns (RegisterResponse);
  rpc Login (LoginRequest) returns (LoginResponse);
  rpc ValidateToken (ValidateTokenRequest) returns (ValidateTokenResponse);
  rpc ListUsers (ListUsersRequest) returns (ListUsersResponse);
  rpc RefreshToken (RefreshTokenRequest) returns (RefreshTokenResponse);
  rpc ListSessions (ListSessionsRequest) returns (ListSessionsResponse);
  rpc RevokeSession (RevokeSessionRequest) returns (RevokeSessionResponse);
  rpc AssignRole (AssignRoleRequest) returns (AssignRoleResponse);
}

message RegisterRequest {
  string email = 1 [(validate.rules).string.email = true];
  string password = 2 [(validate.rules).string.min_len = 8];
  string first_name = 3;
  string last_name = 4;
  string role = 5;
  int64 university_id = 6;
  int64 department_id = 7;
}

message RegisterResponse {
  int64 user_id = 1;
}

message LoginRequest {
  string email = 1;
  string password = 2;
  string user_agent = 3;
  string ip_address = 4;
}

message LoginResponse {
  string access_token = 1;
  string refresh_token = 2;
}

message ValidateTokenRequest {
  string token = 1;
}

message ValidateTokenResponse {
  int64 status = 1;
  string error = 2;
  int64 user_id = 3;
  string role = 4;
  int64 university_id = 5;
  int64 department_id = 6;
}

message ListUsersRequest {
  int64 university_id = 1;
  string role = 2;
  int32 page = 3;
  int32 page_size = 4;
  int64 exclude_user_id = 5;
}

message UserPreview {
  int64 id = 1;
  string email = 2;
  string first_name = 3;
  string last_name = 4;
  string role = 5;
  int64 university_id = 6;
  int64 department_id = 7;
}

message ListUsersResponse {
  repeated UserPreview users = 1;
  int64 total_count = 2;
}
message RefreshTokenRequest {
  string refresh_token = 1;
  string user_agent = 2;
  string ip_address = 3;
}

message RefreshTokenResponse {
  string access_token = 1;
  string refresh_token = 2;
}
message ListSessionsRequest {
  int64 user_id = 1;
}
message Session {
  uint64 id = 1;
  string user_agent = 2;
  string ip_address = 3;
  string created_at = 4;
  string expires_at = 5;
  bool is_current = 6;
}

message ListSessionsResponse {
  repeated Session sessions = 1;
}

message RevokeSessionRequest {
  int64 user_id = 1;
  uint64 session_id = 2;
}

message RevokeSessionResponse {
  bool success = 1;
}
message AssignRoleRequest {
  int64 user_id = 1;
  string role = 2;
}

message AssignRoleResponse {
  bool success = 1;
  string message = 2;
}