// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/protobuf/workflow/v1/workflow.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DepartmentId  int64                  `protobuf:"varint,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_workflow_v1_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *Workflow) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Workflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workflow) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

type Stage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	WorkflowId        int64                  `protobuf:"varint,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Order             int64                  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	ResponsibleRoleId int64                  `protobuf:"varint,5,opt,name=responsible_role_id,json=responsibleRoleId,proto3" json:"responsible_role_id,omitempty"`
	DeadlineDays      int64                  `protobuf:"varint,6,opt,name=deadline_days,json=deadlineDays,proto3" json:"deadline_days,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Stage) Reset() {
	*x = Stage{}
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_workflow_v1_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *Stage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Stage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stage) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *Stage) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Stage) GetResponsibleRoleId() int64 {
	if x != nil {
		return x.ResponsibleRoleId
	}
	return 0
}

func (x *Stage) GetDeadlineDays() int64 {
	if x != nil {
		return x.DeadlineDays
	}
	return 0
}

type CreateWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DepartmentId  int64                  `protobuf:"varint,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowRequest) Reset() {
	*x = CreateWorkflowRequest{}
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowRequest) ProtoMessage() {}

func (x *CreateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_workflow_v1_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWorkflowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkflowRequest) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

type CreateWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      *Workflow              `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowResponse) Reset() {
	*x = CreateWorkflowResponse{}
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowResponse) ProtoMessage() {}

func (x *CreateWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_workflow_v1_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWorkflowResponse) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

type GetWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  int64                  `protobuf:"varint,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRequest) Reset() {
	*x = GetWorkflowRequest{}
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRequest) ProtoMessage() {}

func (x *GetWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_workflow_v1_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkflowRequest) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

type GetWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      *Workflow              `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Stages        []*Stage               `protobuf:"bytes,2,rep,name=stages,proto3" json:"stages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowResponse) Reset() {
	*x = GetWorkflowResponse{}
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowResponse) ProtoMessage() {}

func (x *GetWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_workflow_v1_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkflowResponse) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *GetWorkflowResponse) GetStages() []*Stage {
	if x != nil {
		return x.Stages
	}
	return nil
}

type CreateStageRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	WorkflowId        int64                  `protobuf:"varint,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Order             int64                  `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	ResponsibleRoleId int64                  `protobuf:"varint,4,opt,name=responsible_role_id,json=responsibleRoleId,proto3" json:"responsible_role_id,omitempty"`
	DeadlineDays      int64                  `protobuf:"varint,5,opt,name=deadline_days,json=deadlineDays,proto3" json:"deadline_days,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateStageRequest) Reset() {
	*x = CreateStageRequest{}
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStageRequest) ProtoMessage() {}

func (x *CreateStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStageRequest.ProtoReflect.Descriptor instead.
func (*CreateStageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_workflow_v1_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *CreateStageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStageRequest) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *CreateStageRequest) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *CreateStageRequest) GetResponsibleRoleId() int64 {
	if x != nil {
		return x.ResponsibleRoleId
	}
	return 0
}

func (x *CreateStageRequest) GetDeadlineDays() int64 {
	if x != nil {
		return x.DeadlineDays
	}
	return 0
}

type CreateStageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         *Stage                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStageResponse) Reset() {
	*x = CreateStageResponse{}
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStageResponse) ProtoMessage() {}

func (x *CreateStageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStageResponse.ProtoReflect.Descriptor instead.
func (*CreateStageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_workflow_v1_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *CreateStageResponse) GetStage() *Stage {
	if x != nil {
		return x.Stage
	}
	return nil
}

type GetStageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StageId       int64                  `protobuf:"varint,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStageRequest) Reset() {
	*x = GetStageRequest{}
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStageRequest) ProtoMessage() {}

func (x *GetStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStageRequest.ProtoReflect.Descriptor instead.
func (*GetStageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_workflow_v1_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *GetStageRequest) GetStageId() int64 {
	if x != nil {
		return x.StageId
	}
	return 0
}

type GetStageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         *Stage                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStageResponse) Reset() {
	*x = GetStageResponse{}
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStageResponse) ProtoMessage() {}

func (x *GetStageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStageResponse.ProtoReflect.Descriptor instead.
func (*GetStageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_workflow_v1_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *GetStageResponse) GetStage() *Stage {
	if x != nil {
		return x.Stage
	}
	return nil
}

type GetNextStageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentStageId int64                  `protobuf:"varint,1,opt,name=current_stage_id,json=currentStageId,proto3" json:"current_stage_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNextStageRequest) Reset() {
	*x = GetNextStageRequest{}
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextStageRequest) ProtoMessage() {}

func (x *GetNextStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextStageRequest.ProtoReflect.Descriptor instead.
func (*GetNextStageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_workflow_v1_workflow_proto_rawDescGZIP(), []int{10}
}

func (x *GetNextStageRequest) GetCurrentStageId() int64 {
	if x != nil {
		return x.CurrentStageId
	}
	return 0
}

type GetNextStageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextStageId   int64                  `protobuf:"varint,1,opt,name=next_stage_id,json=nextStageId,proto3" json:"next_stage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextStageResponse) Reset() {
	*x = GetNextStageResponse{}
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextStageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextStageResponse) ProtoMessage() {}

func (x *GetNextStageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextStageResponse.ProtoReflect.Descriptor instead.
func (*GetNextStageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_workflow_v1_workflow_proto_rawDescGZIP(), []int{11}
}

func (x *GetNextStageResponse) GetNextStageId() int64 {
	if x != nil {
		return x.NextStageId
	}
	return 0
}

var File_pkg_protobuf_workflow_v1_workflow_proto protoreflect.FileDescriptor

const file_pkg_protobuf_workflow_v1_workflow_proto_rawDesc = "" +
	"\n" +
	"'pkg/protobuf/workflow/v1/workflow.proto\x12\vworkflow.v1\"S\n" +
	"\bWorkflow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rdepartment_id\x18\x03 \x01(\x03R\fdepartmentId\"\xb7\x01\n" +
	"\x05Stage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vworkflow_id\x18\x03 \x01(\x03R\n" +
	"workflowId\x12\x14\n" +
	"\x05order\x18\x04 \x01(\x03R\x05order\x12.\n" +
	"\x13responsible_role_id\x18\x05 \x01(\x03R\x11responsibleRoleId\x12#\n" +
	"\rdeadline_days\x18\x06 \x01(\x03R\fdeadlineDays\"P\n" +
	"\x15CreateWorkflowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\x03R\fdepartmentId\"K\n" +
	"\x16CreateWorkflowResponse\x121\n" +
	"\bworkflow\x18\x01 \x01(\v2\x15.workflow.v1.WorkflowR\bworkflow\"9\n" +
	"\x12GetWorkflowRequest\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\x03R\fdepartmentId\"t\n" +
	"\x13GetWorkflowResponse\x121\n" +
	"\bworkflow\x18\x01 \x01(\v2\x15.workflow.v1.WorkflowR\bworkflow\x12*\n" +
	"\x06stages\x18\x02 \x03(\v2\x12.workflow.v1.StageR\x06stages\"\xb4\x01\n" +
	"\x12CreateStageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\x03R\n" +
	"workflowId\x12\x14\n" +
	"\x05order\x18\x03 \x01(\x03R\x05order\x12.\n" +
	"\x13responsible_role_id\x18\x04 \x01(\x03R\x11responsibleRoleId\x12#\n" +
	"\rdeadline_days\x18\x05 \x01(\x03R\fdeadlineDays\"?\n" +
	"\x13CreateStageResponse\x12(\n" +
	"\x05stage\x18\x01 \x01(\v2\x12.workflow.v1.StageR\x05stage\",\n" +
	"\x0fGetStageRequest\x12\x19\n" +
	"\bstage_id\x18\x01 \x01(\x03R\astageId\"<\n" +
	"\x10GetStageResponse\x12(\n" +
	"\x05stage\x18\x01 \x01(\v2\x12.workflow.v1.StageR\x05stage\"?\n" +
	"\x13GetNextStageRequest\x12(\n" +
	"\x10current_stage_id\x18\x01 \x01(\x03R\x0ecurrentStageId\":\n" +
	"\x14GetNextStageResponse\x12\"\n" +
	"\rnext_stage_id\x18\x01 \x01(\x03R\vnextStageId2\xae\x03\n" +
	"\x0fWorkflowService\x12Y\n" +
	"\x0eCreateWorkflow\x12\".workflow.v1.CreateWorkflowRequest\x1a#.workflow.v1.CreateWorkflowResponse\x12P\n" +
	"\vGetWorkflow\x12\x1f.workflow.v1.GetWorkflowRequest\x1a .workflow.v1.GetWorkflowResponse\x12P\n" +
	"\vCreateStage\x12\x1f.workflow.v1.CreateStageRequest\x1a .workflow.v1.CreateStageResponse\x12G\n" +
	"\bGetStage\x12\x1c.workflow.v1.GetStageRequest\x1a\x1d.workflow.v1.GetStageResponse\x12S\n" +
	"\fGetNextStage\x12 .workflow.v1.GetNextStageRequest\x1a!.workflow.v1.GetNextStageResponseB\x1aZ\x18pkg/protobuf/workflow/v1b\x06proto3"

var (
	file_pkg_protobuf_workflow_v1_workflow_proto_rawDescOnce sync.Once
	file_pkg_protobuf_workflow_v1_workflow_proto_rawDescData []byte
)

func file_pkg_protobuf_workflow_v1_workflow_proto_rawDescGZIP() []byte {
	file_pkg_protobuf_workflow_v1_workflow_proto_rawDescOnce.Do(func() {
		file_pkg_protobuf_workflow_v1_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protobuf_workflow_v1_workflow_proto_rawDesc), len(file_pkg_protobuf_workflow_v1_workflow_proto_rawDesc)))
	})
	return file_pkg_protobuf_workflow_v1_workflow_proto_rawDescData
}

var file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_protobuf_workflow_v1_workflow_proto_goTypes = []any{
	(*Workflow)(nil),               // 0: workflow.v1.Workflow
	(*Stage)(nil),                  // 1: workflow.v1.Stage
	(*CreateWorkflowRequest)(nil),  // 2: workflow.v1.CreateWorkflowRequest
	(*CreateWorkflowResponse)(nil), // 3: workflow.v1.CreateWorkflowResponse
	(*GetWorkflowRequest)(nil),     // 4: workflow.v1.GetWorkflowRequest
	(*GetWorkflowResponse)(nil),    // 5: workflow.v1.GetWorkflowResponse
	(*CreateStageRequest)(nil),     // 6: workflow.v1.CreateStageRequest
	(*CreateStageResponse)(nil),    // 7: workflow.v1.CreateStageResponse
	(*GetStageRequest)(nil),        // 8: workflow.v1.GetStageRequest
	(*GetStageResponse)(nil),       // 9: workflow.v1.GetStageResponse
	(*GetNextStageRequest)(nil),    // 10: workflow.v1.GetNextStageRequest
	(*GetNextStageResponse)(nil),   // 11: workflow.v1.GetNextStageResponse
}
var file_pkg_protobuf_workflow_v1_workflow_proto_depIdxs = []int32{
	0,  // 0: workflow.v1.CreateWorkflowResponse.workflow:type_name -> workflow.v1.Workflow
	0,  // 1: workflow.v1.GetWorkflowResponse.workflow:type_name -> workflow.v1.Workflow
	1,  // 2: workflow.v1.GetWorkflowResponse.stages:type_name -> workflow.v1.Stage
	1,  // 3: workflow.v1.CreateStageResponse.stage:type_name -> workflow.v1.Stage
	1,  // 4: workflow.v1.GetStageResponse.stage:type_name -> workflow.v1.Stage
	2,  // 5: workflow.v1.WorkflowService.CreateWorkflow:input_type -> workflow.v1.CreateWorkflowRequest
	4,  // 6: workflow.v1.WorkflowService.GetWorkflow:input_type -> workflow.v1.GetWorkflowRequest
	6,  // 7: workflow.v1.WorkflowService.CreateStage:input_type -> workflow.v1.CreateStageRequest
	8,  // 8: workflow.v1.WorkflowService.GetStage:input_type -> workflow.v1.GetStageRequest
	10, // 9: workflow.v1.WorkflowService.GetNextStage:input_type -> workflow.v1.GetNextStageRequest
	3,  // 10: workflow.v1.WorkflowService.CreateWorkflow:output_type -> workflow.v1.CreateWorkflowResponse
	5,  // 11: workflow.v1.WorkflowService.GetWorkflow:output_type -> workflow.v1.GetWorkflowResponse
	7,  // 12: workflow.v1.WorkflowService.CreateStage:output_type -> workflow.v1.CreateStageResponse
	9,  // 13: workflow.v1.WorkflowService.GetStage:output_type -> workflow.v1.GetStageResponse
	11, // 14: workflow.v1.WorkflowService.GetNextStage:output_type -> workflow.v1.GetNextStageResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_protobuf_workflow_v1_workflow_proto_init() }
func file_pkg_protobuf_workflow_v1_workflow_proto_init() {
	if File_pkg_protobuf_workflow_v1_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protobuf_workflow_v1_workflow_proto_rawDesc), len(file_pkg_protobuf_workflow_v1_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protobuf_workflow_v1_workflow_proto_goTypes,
		DependencyIndexes: file_pkg_protobuf_workflow_v1_workflow_proto_depIdxs,
		MessageInfos:      file_pkg_protobuf_workflow_v1_workflow_proto_msgTypes,
	}.Build()
	File_pkg_protobuf_workflow_v1_workflow_proto = out.File
	file_pkg_protobuf_workflow_v1_workflow_proto_goTypes = nil
	file_pkg_protobuf_workflow_v1_workflow_proto_depIdxs = nil
}
