// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: workflow/v1/workflow_admin.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkflowAdminService_CreateDepartmentConfig_FullMethodName     = "/workflow.v1.WorkflowAdminService/CreateDepartmentConfig"
	WorkflowAdminService_GetDepartmentConfig_FullMethodName        = "/workflow.v1.WorkflowAdminService/GetDepartmentConfig"
	WorkflowAdminService_ListDepartmentConfigs_FullMethodName      = "/workflow.v1.WorkflowAdminService/ListDepartmentConfigs"
	WorkflowAdminService_UpdateDepartmentConfig_FullMethodName     = "/workflow.v1.WorkflowAdminService/UpdateDepartmentConfig"
	WorkflowAdminService_ActivateDepartmentConfig_FullMethodName   = "/workflow.v1.WorkflowAdminService/ActivateDepartmentConfig"
	WorkflowAdminService_DeleteDepartmentConfig_FullMethodName     = "/workflow.v1.WorkflowAdminService/DeleteDepartmentConfig"
	WorkflowAdminService_AddCustomStep_FullMethodName              = "/workflow.v1.WorkflowAdminService/AddCustomStep"
	WorkflowAdminService_UpdateCustomStep_FullMethodName           = "/workflow.v1.WorkflowAdminService/UpdateCustomStep"
	WorkflowAdminService_DeleteCustomStep_FullMethodName           = "/workflow.v1.WorkflowAdminService/DeleteCustomStep"
	WorkflowAdminService_ReorderCustomSteps_FullMethodName         = "/workflow.v1.WorkflowAdminService/ReorderCustomSteps"
	WorkflowAdminService_ListAvailableActions_FullMethodName       = "/workflow.v1.WorkflowAdminService/ListAvailableActions"
	WorkflowAdminService_GetActionSchema_FullMethodName            = "/workflow.v1.WorkflowAdminService/GetActionSchema"
	WorkflowAdminService_GetWorkflowBuilder_FullMethodName         = "/workflow.v1.WorkflowAdminService/GetWorkflowBuilder"
	WorkflowAdminService_SaveWorkflowDraft_FullMethodName          = "/workflow.v1.WorkflowAdminService/SaveWorkflowDraft"
	WorkflowAdminService_PublishWorkflow_FullMethodName            = "/workflow.v1.WorkflowAdminService/PublishWorkflow"
	WorkflowAdminService_PreviewWorkflow_FullMethodName            = "/workflow.v1.WorkflowAdminService/PreviewWorkflow"
	WorkflowAdminService_SimulateTransition_FullMethodName         = "/workflow.v1.WorkflowAdminService/SimulateTransition"
	WorkflowAdminService_ProcessWorkflowActionEvent_FullMethodName = "/workflow.v1.WorkflowAdminService/ProcessWorkflowActionEvent"
)

// WorkflowAdminServiceClient is the client API for WorkflowAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== ADMIN API ====================
type WorkflowAdminServiceClient interface {
	// Department Configs
	CreateDepartmentConfig(ctx context.Context, in *CreateDepartmentConfigRequest, opts ...grpc.CallOption) (*DepartmentConfig, error)
	GetDepartmentConfig(ctx context.Context, in *GetDepartmentConfigRequest, opts ...grpc.CallOption) (*DepartmentConfig, error)
	ListDepartmentConfigs(ctx context.Context, in *ListDepartmentConfigsRequest, opts ...grpc.CallOption) (*ListDepartmentConfigsResponse, error)
	UpdateDepartmentConfig(ctx context.Context, in *UpdateDepartmentConfigRequest, opts ...grpc.CallOption) (*DepartmentConfig, error)
	ActivateDepartmentConfig(ctx context.Context, in *ActivateDepartmentConfigRequest, opts ...grpc.CallOption) (*DepartmentConfig, error)
	DeleteDepartmentConfig(ctx context.Context, in *DeleteDepartmentConfigRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Custom Steps
	AddCustomStep(ctx context.Context, in *AddCustomStepRequest, opts ...grpc.CallOption) (*CustomStep, error)
	UpdateCustomStep(ctx context.Context, in *UpdateCustomStepRequest, opts ...grpc.CallOption) (*CustomStep, error)
	DeleteCustomStep(ctx context.Context, in *DeleteCustomStepRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReorderCustomSteps(ctx context.Context, in *ReorderCustomStepsRequest, opts ...grpc.CallOption) (*ListCustomStepsResponse, error)
	// Action Registry
	ListAvailableActions(ctx context.Context, in *ListAvailableActionsRequest, opts ...grpc.CallOption) (*ListAvailableActionsResponse, error)
	GetActionSchema(ctx context.Context, in *GetActionSchemaRequest, opts ...grpc.CallOption) (*ActionSchema, error)
	// Workflow Builder
	GetWorkflowBuilder(ctx context.Context, in *GetWorkflowBuilderRequest, opts ...grpc.CallOption) (*WorkflowBuilderResponse, error)
	SaveWorkflowDraft(ctx context.Context, in *SaveWorkflowDraftRequest, opts ...grpc.CallOption) (*Workflow, error)
	PublishWorkflow(ctx context.Context, in *PublishWorkflowRequest, opts ...grpc.CallOption) (*Workflow, error)
	// Preview & Test
	PreviewWorkflow(ctx context.Context, in *PreviewWorkflowRequest, opts ...grpc.CallOption) (*WorkflowPreview, error)
	SimulateTransition(ctx context.Context, in *SimulateTransitionRequest, opts ...grpc.CallOption) (*SimulateTransitionResponse, error)
	// NOTE: использует сообщения из workflow.proto (ProcessWorkflowActionEventRequest/Response)
	ProcessWorkflowActionEvent(ctx context.Context, in *ProcessWorkflowActionEventRequest, opts ...grpc.CallOption) (*ProcessWorkflowActionEventResponse, error)
}

type workflowAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowAdminServiceClient(cc grpc.ClientConnInterface) WorkflowAdminServiceClient {
	return &workflowAdminServiceClient{cc}
}

func (c *workflowAdminServiceClient) CreateDepartmentConfig(ctx context.Context, in *CreateDepartmentConfigRequest, opts ...grpc.CallOption) (*DepartmentConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepartmentConfig)
	err := c.cc.Invoke(ctx, WorkflowAdminService_CreateDepartmentConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdminServiceClient) GetDepartmentConfig(ctx context.Context, in *GetDepartmentConfigRequest, opts ...grpc.CallOption) (*DepartmentConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepartmentConfig)
	err := c.cc.Invoke(ctx, WorkflowAdminService_GetDepartmentConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdminServiceClient) ListDepartmentConfigs(ctx context.Context, in *ListDepartmentConfigsRequest, opts ...grpc.CallOption) (*ListDepartmentConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDepartmentConfigsResponse)
	err := c.cc.Invoke(ctx, WorkflowAdminService_ListDepartmentConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdminServiceClient) UpdateDepartmentConfig(ctx context.Context, in *UpdateDepartmentConfigRequest, opts ...grpc.CallOption) (*DepartmentConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepartmentConfig)
	err := c.cc.Invoke(ctx, WorkflowAdminService_UpdateDepartmentConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdminServiceClient) ActivateDepartmentConfig(ctx context.Context, in *ActivateDepartmentConfigRequest, opts ...grpc.CallOption) (*DepartmentConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepartmentConfig)
	err := c.cc.Invoke(ctx, WorkflowAdminService_ActivateDepartmentConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdminServiceClient) DeleteDepartmentConfig(ctx context.Context, in *DeleteDepartmentConfigRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkflowAdminService_DeleteDepartmentConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdminServiceClient) AddCustomStep(ctx context.Context, in *AddCustomStepRequest, opts ...grpc.CallOption) (*CustomStep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomStep)
	err := c.cc.Invoke(ctx, WorkflowAdminService_AddCustomStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdminServiceClient) UpdateCustomStep(ctx context.Context, in *UpdateCustomStepRequest, opts ...grpc.CallOption) (*CustomStep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomStep)
	err := c.cc.Invoke(ctx, WorkflowAdminService_UpdateCustomStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdminServiceClient) DeleteCustomStep(ctx context.Context, in *DeleteCustomStepRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkflowAdminService_DeleteCustomStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdminServiceClient) ReorderCustomSteps(ctx context.Context, in *ReorderCustomStepsRequest, opts ...grpc.CallOption) (*ListCustomStepsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCustomStepsResponse)
	err := c.cc.Invoke(ctx, WorkflowAdminService_ReorderCustomSteps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdminServiceClient) ListAvailableActions(ctx context.Context, in *ListAvailableActionsRequest, opts ...grpc.CallOption) (*ListAvailableActionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAvailableActionsResponse)
	err := c.cc.Invoke(ctx, WorkflowAdminService_ListAvailableActions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdminServiceClient) GetActionSchema(ctx context.Context, in *GetActionSchemaRequest, opts ...grpc.CallOption) (*ActionSchema, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionSchema)
	err := c.cc.Invoke(ctx, WorkflowAdminService_GetActionSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdminServiceClient) GetWorkflowBuilder(ctx context.Context, in *GetWorkflowBuilderRequest, opts ...grpc.CallOption) (*WorkflowBuilderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowBuilderResponse)
	err := c.cc.Invoke(ctx, WorkflowAdminService_GetWorkflowBuilder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdminServiceClient) SaveWorkflowDraft(ctx context.Context, in *SaveWorkflowDraftRequest, opts ...grpc.CallOption) (*Workflow, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workflow)
	err := c.cc.Invoke(ctx, WorkflowAdminService_SaveWorkflowDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdminServiceClient) PublishWorkflow(ctx context.Context, in *PublishWorkflowRequest, opts ...grpc.CallOption) (*Workflow, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workflow)
	err := c.cc.Invoke(ctx, WorkflowAdminService_PublishWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdminServiceClient) PreviewWorkflow(ctx context.Context, in *PreviewWorkflowRequest, opts ...grpc.CallOption) (*WorkflowPreview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowPreview)
	err := c.cc.Invoke(ctx, WorkflowAdminService_PreviewWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdminServiceClient) SimulateTransition(ctx context.Context, in *SimulateTransitionRequest, opts ...grpc.CallOption) (*SimulateTransitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulateTransitionResponse)
	err := c.cc.Invoke(ctx, WorkflowAdminService_SimulateTransition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowAdminServiceClient) ProcessWorkflowActionEvent(ctx context.Context, in *ProcessWorkflowActionEventRequest, opts ...grpc.CallOption) (*ProcessWorkflowActionEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessWorkflowActionEventResponse)
	err := c.cc.Invoke(ctx, WorkflowAdminService_ProcessWorkflowActionEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowAdminServiceServer is the server API for WorkflowAdminService service.
// All implementations must embed UnimplementedWorkflowAdminServiceServer
// for forward compatibility.
//
// ==================== ADMIN API ====================
type WorkflowAdminServiceServer interface {
	// Department Configs
	CreateDepartmentConfig(context.Context, *CreateDepartmentConfigRequest) (*DepartmentConfig, error)
	GetDepartmentConfig(context.Context, *GetDepartmentConfigRequest) (*DepartmentConfig, error)
	ListDepartmentConfigs(context.Context, *ListDepartmentConfigsRequest) (*ListDepartmentConfigsResponse, error)
	UpdateDepartmentConfig(context.Context, *UpdateDepartmentConfigRequest) (*DepartmentConfig, error)
	ActivateDepartmentConfig(context.Context, *ActivateDepartmentConfigRequest) (*DepartmentConfig, error)
	DeleteDepartmentConfig(context.Context, *DeleteDepartmentConfigRequest) (*emptypb.Empty, error)
	// Custom Steps
	AddCustomStep(context.Context, *AddCustomStepRequest) (*CustomStep, error)
	UpdateCustomStep(context.Context, *UpdateCustomStepRequest) (*CustomStep, error)
	DeleteCustomStep(context.Context, *DeleteCustomStepRequest) (*emptypb.Empty, error)
	ReorderCustomSteps(context.Context, *ReorderCustomStepsRequest) (*ListCustomStepsResponse, error)
	// Action Registry
	ListAvailableActions(context.Context, *ListAvailableActionsRequest) (*ListAvailableActionsResponse, error)
	GetActionSchema(context.Context, *GetActionSchemaRequest) (*ActionSchema, error)
	// Workflow Builder
	GetWorkflowBuilder(context.Context, *GetWorkflowBuilderRequest) (*WorkflowBuilderResponse, error)
	SaveWorkflowDraft(context.Context, *SaveWorkflowDraftRequest) (*Workflow, error)
	PublishWorkflow(context.Context, *PublishWorkflowRequest) (*Workflow, error)
	// Preview & Test
	PreviewWorkflow(context.Context, *PreviewWorkflowRequest) (*WorkflowPreview, error)
	SimulateTransition(context.Context, *SimulateTransitionRequest) (*SimulateTransitionResponse, error)
	// NOTE: использует сообщения из workflow.proto (ProcessWorkflowActionEventRequest/Response)
	ProcessWorkflowActionEvent(context.Context, *ProcessWorkflowActionEventRequest) (*ProcessWorkflowActionEventResponse, error)
	mustEmbedUnimplementedWorkflowAdminServiceServer()
}

// UnimplementedWorkflowAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowAdminServiceServer struct{}

func (UnimplementedWorkflowAdminServiceServer) CreateDepartmentConfig(context.Context, *CreateDepartmentConfigRequest) (*DepartmentConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDepartmentConfig not implemented")
}
func (UnimplementedWorkflowAdminServiceServer) GetDepartmentConfig(context.Context, *GetDepartmentConfigRequest) (*DepartmentConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDepartmentConfig not implemented")
}
func (UnimplementedWorkflowAdminServiceServer) ListDepartmentConfigs(context.Context, *ListDepartmentConfigsRequest) (*ListDepartmentConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDepartmentConfigs not implemented")
}
func (UnimplementedWorkflowAdminServiceServer) UpdateDepartmentConfig(context.Context, *UpdateDepartmentConfigRequest) (*DepartmentConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDepartmentConfig not implemented")
}
func (UnimplementedWorkflowAdminServiceServer) ActivateDepartmentConfig(context.Context, *ActivateDepartmentConfigRequest) (*DepartmentConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateDepartmentConfig not implemented")
}
func (UnimplementedWorkflowAdminServiceServer) DeleteDepartmentConfig(context.Context, *DeleteDepartmentConfigRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDepartmentConfig not implemented")
}
func (UnimplementedWorkflowAdminServiceServer) AddCustomStep(context.Context, *AddCustomStepRequest) (*CustomStep, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCustomStep not implemented")
}
func (UnimplementedWorkflowAdminServiceServer) UpdateCustomStep(context.Context, *UpdateCustomStepRequest) (*CustomStep, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCustomStep not implemented")
}
func (UnimplementedWorkflowAdminServiceServer) DeleteCustomStep(context.Context, *DeleteCustomStepRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCustomStep not implemented")
}
func (UnimplementedWorkflowAdminServiceServer) ReorderCustomSteps(context.Context, *ReorderCustomStepsRequest) (*ListCustomStepsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReorderCustomSteps not implemented")
}
func (UnimplementedWorkflowAdminServiceServer) ListAvailableActions(context.Context, *ListAvailableActionsRequest) (*ListAvailableActionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAvailableActions not implemented")
}
func (UnimplementedWorkflowAdminServiceServer) GetActionSchema(context.Context, *GetActionSchemaRequest) (*ActionSchema, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActionSchema not implemented")
}
func (UnimplementedWorkflowAdminServiceServer) GetWorkflowBuilder(context.Context, *GetWorkflowBuilderRequest) (*WorkflowBuilderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkflowBuilder not implemented")
}
func (UnimplementedWorkflowAdminServiceServer) SaveWorkflowDraft(context.Context, *SaveWorkflowDraftRequest) (*Workflow, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveWorkflowDraft not implemented")
}
func (UnimplementedWorkflowAdminServiceServer) PublishWorkflow(context.Context, *PublishWorkflowRequest) (*Workflow, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishWorkflow not implemented")
}
func (UnimplementedWorkflowAdminServiceServer) PreviewWorkflow(context.Context, *PreviewWorkflowRequest) (*WorkflowPreview, error) {
	return nil, status.Error(codes.Unimplemented, "method PreviewWorkflow not implemented")
}
func (UnimplementedWorkflowAdminServiceServer) SimulateTransition(context.Context, *SimulateTransitionRequest) (*SimulateTransitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SimulateTransition not implemented")
}
func (UnimplementedWorkflowAdminServiceServer) ProcessWorkflowActionEvent(context.Context, *ProcessWorkflowActionEventRequest) (*ProcessWorkflowActionEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessWorkflowActionEvent not implemented")
}
func (UnimplementedWorkflowAdminServiceServer) mustEmbedUnimplementedWorkflowAdminServiceServer() {}
func (UnimplementedWorkflowAdminServiceServer) testEmbeddedByValue()                              {}

// UnsafeWorkflowAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowAdminServiceServer will
// result in compilation errors.
type UnsafeWorkflowAdminServiceServer interface {
	mustEmbedUnimplementedWorkflowAdminServiceServer()
}

func RegisterWorkflowAdminServiceServer(s grpc.ServiceRegistrar, srv WorkflowAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkflowAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkflowAdminService_ServiceDesc, srv)
}

func _WorkflowAdminService_CreateDepartmentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDepartmentConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdminServiceServer).CreateDepartmentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdminService_CreateDepartmentConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdminServiceServer).CreateDepartmentConfig(ctx, req.(*CreateDepartmentConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdminService_GetDepartmentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepartmentConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdminServiceServer).GetDepartmentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdminService_GetDepartmentConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdminServiceServer).GetDepartmentConfig(ctx, req.(*GetDepartmentConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdminService_ListDepartmentConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDepartmentConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdminServiceServer).ListDepartmentConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdminService_ListDepartmentConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdminServiceServer).ListDepartmentConfigs(ctx, req.(*ListDepartmentConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdminService_UpdateDepartmentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDepartmentConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdminServiceServer).UpdateDepartmentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdminService_UpdateDepartmentConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdminServiceServer).UpdateDepartmentConfig(ctx, req.(*UpdateDepartmentConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdminService_ActivateDepartmentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateDepartmentConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdminServiceServer).ActivateDepartmentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdminService_ActivateDepartmentConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdminServiceServer).ActivateDepartmentConfig(ctx, req.(*ActivateDepartmentConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdminService_DeleteDepartmentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDepartmentConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdminServiceServer).DeleteDepartmentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdminService_DeleteDepartmentConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdminServiceServer).DeleteDepartmentConfig(ctx, req.(*DeleteDepartmentConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdminService_AddCustomStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCustomStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdminServiceServer).AddCustomStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdminService_AddCustomStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdminServiceServer).AddCustomStep(ctx, req.(*AddCustomStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdminService_UpdateCustomStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCustomStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdminServiceServer).UpdateCustomStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdminService_UpdateCustomStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdminServiceServer).UpdateCustomStep(ctx, req.(*UpdateCustomStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdminService_DeleteCustomStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCustomStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdminServiceServer).DeleteCustomStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdminService_DeleteCustomStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdminServiceServer).DeleteCustomStep(ctx, req.(*DeleteCustomStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdminService_ReorderCustomSteps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReorderCustomStepsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdminServiceServer).ReorderCustomSteps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdminService_ReorderCustomSteps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdminServiceServer).ReorderCustomSteps(ctx, req.(*ReorderCustomStepsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdminService_ListAvailableActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAvailableActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdminServiceServer).ListAvailableActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdminService_ListAvailableActions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdminServiceServer).ListAvailableActions(ctx, req.(*ListAvailableActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdminService_GetActionSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActionSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdminServiceServer).GetActionSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdminService_GetActionSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdminServiceServer).GetActionSchema(ctx, req.(*GetActionSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdminService_GetWorkflowBuilder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowBuilderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdminServiceServer).GetWorkflowBuilder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdminService_GetWorkflowBuilder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdminServiceServer).GetWorkflowBuilder(ctx, req.(*GetWorkflowBuilderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdminService_SaveWorkflowDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveWorkflowDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdminServiceServer).SaveWorkflowDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdminService_SaveWorkflowDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdminServiceServer).SaveWorkflowDraft(ctx, req.(*SaveWorkflowDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdminService_PublishWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdminServiceServer).PublishWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdminService_PublishWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdminServiceServer).PublishWorkflow(ctx, req.(*PublishWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdminService_PreviewWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdminServiceServer).PreviewWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdminService_PreviewWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdminServiceServer).PreviewWorkflow(ctx, req.(*PreviewWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdminService_SimulateTransition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulateTransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdminServiceServer).SimulateTransition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdminService_SimulateTransition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdminServiceServer).SimulateTransition(ctx, req.(*SimulateTransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowAdminService_ProcessWorkflowActionEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessWorkflowActionEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowAdminServiceServer).ProcessWorkflowActionEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowAdminService_ProcessWorkflowActionEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowAdminServiceServer).ProcessWorkflowActionEvent(ctx, req.(*ProcessWorkflowActionEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowAdminService_ServiceDesc is the grpc.ServiceDesc for WorkflowAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workflow.v1.WorkflowAdminService",
	HandlerType: (*WorkflowAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDepartmentConfig",
			Handler:    _WorkflowAdminService_CreateDepartmentConfig_Handler,
		},
		{
			MethodName: "GetDepartmentConfig",
			Handler:    _WorkflowAdminService_GetDepartmentConfig_Handler,
		},
		{
			MethodName: "ListDepartmentConfigs",
			Handler:    _WorkflowAdminService_ListDepartmentConfigs_Handler,
		},
		{
			MethodName: "UpdateDepartmentConfig",
			Handler:    _WorkflowAdminService_UpdateDepartmentConfig_Handler,
		},
		{
			MethodName: "ActivateDepartmentConfig",
			Handler:    _WorkflowAdminService_ActivateDepartmentConfig_Handler,
		},
		{
			MethodName: "DeleteDepartmentConfig",
			Handler:    _WorkflowAdminService_DeleteDepartmentConfig_Handler,
		},
		{
			MethodName: "AddCustomStep",
			Handler:    _WorkflowAdminService_AddCustomStep_Handler,
		},
		{
			MethodName: "UpdateCustomStep",
			Handler:    _WorkflowAdminService_UpdateCustomStep_Handler,
		},
		{
			MethodName: "DeleteCustomStep",
			Handler:    _WorkflowAdminService_DeleteCustomStep_Handler,
		},
		{
			MethodName: "ReorderCustomSteps",
			Handler:    _WorkflowAdminService_ReorderCustomSteps_Handler,
		},
		{
			MethodName: "ListAvailableActions",
			Handler:    _WorkflowAdminService_ListAvailableActions_Handler,
		},
		{
			MethodName: "GetActionSchema",
			Handler:    _WorkflowAdminService_GetActionSchema_Handler,
		},
		{
			MethodName: "GetWorkflowBuilder",
			Handler:    _WorkflowAdminService_GetWorkflowBuilder_Handler,
		},
		{
			MethodName: "SaveWorkflowDraft",
			Handler:    _WorkflowAdminService_SaveWorkflowDraft_Handler,
		},
		{
			MethodName: "PublishWorkflow",
			Handler:    _WorkflowAdminService_PublishWorkflow_Handler,
		},
		{
			MethodName: "PreviewWorkflow",
			Handler:    _WorkflowAdminService_PreviewWorkflow_Handler,
		},
		{
			MethodName: "SimulateTransition",
			Handler:    _WorkflowAdminService_SimulateTransition_Handler,
		},
		{
			MethodName: "ProcessWorkflowActionEvent",
			Handler:    _WorkflowAdminService_ProcessWorkflowActionEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workflow/v1/workflow_admin.proto",
}
