// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: workflow/v1/workflow.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateType int32

const (
	StateType_STATE_TYPE_UNSPECIFIED StateType = 0
	StateType_TEAM_FORMATION         StateType = 1
	StateType_SUPERVISOR_SELECTION   StateType = 2
	StateType_DOCUMENT_UPLOAD        StateType = 3
	StateType_FORM_FILLING           StateType = 4
	StateType_EXTERNAL_CHECK         StateType = 5
	StateType_APPROVAL               StateType = 6
)

// Enum value maps for StateType.
var (
	StateType_name = map[int32]string{
		0: "STATE_TYPE_UNSPECIFIED",
		1: "TEAM_FORMATION",
		2: "SUPERVISOR_SELECTION",
		3: "DOCUMENT_UPLOAD",
		4: "FORM_FILLING",
		5: "EXTERNAL_CHECK",
		6: "APPROVAL",
	}
	StateType_value = map[string]int32{
		"STATE_TYPE_UNSPECIFIED": 0,
		"TEAM_FORMATION":         1,
		"SUPERVISOR_SELECTION":   2,
		"DOCUMENT_UPLOAD":        3,
		"FORM_FILLING":           4,
		"EXTERNAL_CHECK":         5,
		"APPROVAL":               6,
	}
)

func (x StateType) Enum() *StateType {
	p := new(StateType)
	*p = x
	return p
}

func (x StateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateType) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_v1_workflow_proto_enumTypes[0].Descriptor()
}

func (StateType) Type() protoreflect.EnumType {
	return &file_workflow_v1_workflow_proto_enumTypes[0]
}

func (x StateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateType.Descriptor instead.
func (StateType) EnumDescriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{0}
}

type StateAction_ActionType int32

const (
	StateAction_ACTION_TYPE_UNSPECIFIED StateAction_ActionType = 0
	StateAction_SEND_NOTIFICATION       StateAction_ActionType = 1
	StateAction_ASSIGN_TASK             StateAction_ActionType = 2
	StateAction_CALL_WEBHOOK            StateAction_ActionType = 3
)

// Enum value maps for StateAction_ActionType.
var (
	StateAction_ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "SEND_NOTIFICATION",
		2: "ASSIGN_TASK",
		3: "CALL_WEBHOOK",
	}
	StateAction_ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED": 0,
		"SEND_NOTIFICATION":       1,
		"ASSIGN_TASK":             2,
		"CALL_WEBHOOK":            3,
	}
)

func (x StateAction_ActionType) Enum() *StateAction_ActionType {
	p := new(StateAction_ActionType)
	*p = x
	return p
}

func (x StateAction_ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateAction_ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_v1_workflow_proto_enumTypes[1].Descriptor()
}

func (StateAction_ActionType) Type() protoreflect.EnumType {
	return &file_workflow_v1_workflow_proto_enumTypes[1]
}

func (x StateAction_ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateAction_ActionType.Descriptor instead.
func (StateAction_ActionType) EnumDescriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{5, 0}
}

type StateAction_Trigger int32

const (
	StateAction_TRIGGER_UNSPECIFIED StateAction_Trigger = 0
	StateAction_ON_ENTER            StateAction_Trigger = 1
	StateAction_ON_EXIT             StateAction_Trigger = 2
	StateAction_ON_DEADLINE         StateAction_Trigger = 3
)

// Enum value maps for StateAction_Trigger.
var (
	StateAction_Trigger_name = map[int32]string{
		0: "TRIGGER_UNSPECIFIED",
		1: "ON_ENTER",
		2: "ON_EXIT",
		3: "ON_DEADLINE",
	}
	StateAction_Trigger_value = map[string]int32{
		"TRIGGER_UNSPECIFIED": 0,
		"ON_ENTER":            1,
		"ON_EXIT":             2,
		"ON_DEADLINE":         3,
	}
)

func (x StateAction_Trigger) Enum() *StateAction_Trigger {
	p := new(StateAction_Trigger)
	*p = x
	return p
}

func (x StateAction_Trigger) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateAction_Trigger) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_v1_workflow_proto_enumTypes[2].Descriptor()
}

func (StateAction_Trigger) Type() protoreflect.EnumType {
	return &file_workflow_v1_workflow_proto_enumTypes[2]
}

func (x StateAction_Trigger) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateAction_Trigger.Descriptor instead.
func (StateAction_Trigger) EnumDescriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{5, 1}
}

// Конфигурация для шага (хранится внутри State.config или парсится отдельно)
type StepConfiguration struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TeamConfig       *TeamConfig            `protobuf:"bytes,1,opt,name=team_config,json=teamConfig,proto3" json:"team_config,omitempty"`
	DeadlineConfig   *DeadlineConfig        `protobuf:"bytes,2,opt,name=deadline_config,json=deadlineConfig,proto3" json:"deadline_config,omitempty"`
	FormSchema       *FormSchema            `protobuf:"bytes,3,opt,name=form_schema,json=formSchema,proto3" json:"form_schema,omitempty"`
	FileRequirements *FileRequirements      `protobuf:"bytes,4,opt,name=file_requirements,json=fileRequirements,proto3" json:"file_requirements,omitempty"`
	AllowedRoles     []string               `protobuf:"bytes,5,rep,name=allowed_roles,json=allowedRoles,proto3" json:"allowed_roles,omitempty"` // Роли, которым доступен этот шаг
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StepConfiguration) Reset() {
	*x = StepConfiguration{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepConfiguration) ProtoMessage() {}

func (x *StepConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepConfiguration.ProtoReflect.Descriptor instead.
func (*StepConfiguration) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *StepConfiguration) GetTeamConfig() *TeamConfig {
	if x != nil {
		return x.TeamConfig
	}
	return nil
}

func (x *StepConfiguration) GetDeadlineConfig() *DeadlineConfig {
	if x != nil {
		return x.DeadlineConfig
	}
	return nil
}

func (x *StepConfiguration) GetFormSchema() *FormSchema {
	if x != nil {
		return x.FormSchema
	}
	return nil
}

func (x *StepConfiguration) GetFileRequirements() *FileRequirements {
	if x != nil {
		return x.FileRequirements
	}
	return nil
}

func (x *StepConfiguration) GetAllowedRoles() []string {
	if x != nil {
		return x.AllowedRoles
	}
	return nil
}

type TeamConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinSize       int32                  `protobuf:"varint,1,opt,name=min_size,json=minSize,proto3" json:"min_size,omitempty"`
	MaxSize       int32                  `protobuf:"varint,2,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	AllowSolo     bool                   `protobuf:"varint,3,opt,name=allow_solo,json=allowSolo,proto3" json:"allow_solo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamConfig) Reset() {
	*x = TeamConfig{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamConfig) ProtoMessage() {}

func (x *TeamConfig) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamConfig.ProtoReflect.Descriptor instead.
func (*TeamConfig) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *TeamConfig) GetMinSize() int32 {
	if x != nil {
		return x.MinSize
	}
	return 0
}

func (x *TeamConfig) GetMaxSize() int32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *TeamConfig) GetAllowSolo() bool {
	if x != nil {
		return x.AllowSolo
	}
	return false
}

type DeadlineConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Дедлайн может быть фиксированной датой или длительностью от начала шага
	//
	// Types that are valid to be assigned to Type:
	//
	//	*DeadlineConfig_FixedDate
	//	*DeadlineConfig_DurationHours
	Type          isDeadlineConfig_Type `protobuf_oneof:"type"`
	Timezone      string                `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"` // e.g., "Asia/Almaty" or "UTC+5"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeadlineConfig) Reset() {
	*x = DeadlineConfig{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeadlineConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadlineConfig) ProtoMessage() {}

func (x *DeadlineConfig) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadlineConfig.ProtoReflect.Descriptor instead.
func (*DeadlineConfig) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *DeadlineConfig) GetType() isDeadlineConfig_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *DeadlineConfig) GetFixedDate() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Type.(*DeadlineConfig_FixedDate); ok {
			return x.FixedDate
		}
	}
	return nil
}

func (x *DeadlineConfig) GetDurationHours() int32 {
	if x != nil {
		if x, ok := x.Type.(*DeadlineConfig_DurationHours); ok {
			return x.DurationHours
		}
	}
	return 0
}

func (x *DeadlineConfig) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type isDeadlineConfig_Type interface {
	isDeadlineConfig_Type()
}

type DeadlineConfig_FixedDate struct {
	FixedDate *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=fixed_date,json=fixedDate,proto3,oneof"`
}

type DeadlineConfig_DurationHours struct {
	DurationHours int32 `protobuf:"varint,2,opt,name=duration_hours,json=durationHours,proto3,oneof"`
}

func (*DeadlineConfig_FixedDate) isDeadlineConfig_Type() {}

func (*DeadlineConfig_DurationHours) isDeadlineConfig_Type() {}

type FormSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormId        string                 `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`             // Уникальный ID формы
	JsonSchema    string                 `protobuf:"bytes,2,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"` // JSON Schema для валидации на фронте и бэке
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormSchema) Reset() {
	*x = FormSchema{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormSchema) ProtoMessage() {}

func (x *FormSchema) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormSchema.ProtoReflect.Descriptor instead.
func (*FormSchema) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *FormSchema) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *FormSchema) GetJsonSchema() string {
	if x != nil {
		return x.JsonSchema
	}
	return ""
}

type FileRequirements struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaxFiles          int32                  `protobuf:"varint,1,opt,name=max_files,json=maxFiles,proto3" json:"max_files,omitempty"`
	AllowedExtensions []string               `protobuf:"bytes,2,rep,name=allowed_extensions,json=allowedExtensions,proto3" json:"allowed_extensions,omitempty"` // e.g. [".pdf", ".docx"]
	MaxSizeBytes      int64                  `protobuf:"varint,3,opt,name=max_size_bytes,json=maxSizeBytes,proto3" json:"max_size_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FileRequirements) Reset() {
	*x = FileRequirements{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequirements) ProtoMessage() {}

func (x *FileRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequirements.ProtoReflect.Descriptor instead.
func (*FileRequirements) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *FileRequirements) GetMaxFiles() int32 {
	if x != nil {
		return x.MaxFiles
	}
	return 0
}

func (x *FileRequirements) GetAllowedExtensions() []string {
	if x != nil {
		return x.AllowedExtensions
	}
	return nil
}

func (x *FileRequirements) GetMaxSizeBytes() int64 {
	if x != nil {
		return x.MaxSizeBytes
	}
	return 0
}

type StateAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StateId       int64                  `protobuf:"varint,2,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	Type          StateAction_ActionType `protobuf:"varint,3,opt,name=type,proto3,enum=workflow.v1.StateAction_ActionType" json:"type,omitempty"`
	Trigger       StateAction_Trigger    `protobuf:"varint,4,opt,name=trigger,proto3,enum=workflow.v1.StateAction_Trigger" json:"trigger,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateAction) Reset() {
	*x = StateAction{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateAction) ProtoMessage() {}

func (x *StateAction) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateAction.ProtoReflect.Descriptor instead.
func (*StateAction) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *StateAction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StateAction) GetStateId() int64 {
	if x != nil {
		return x.StateId
	}
	return 0
}

func (x *StateAction) GetType() StateAction_ActionType {
	if x != nil {
		return x.Type
	}
	return StateAction_ACTION_TYPE_UNSPECIFIED
}

func (x *StateAction) GetTrigger() StateAction_Trigger {
	if x != nil {
		return x.Trigger
	}
	return StateAction_TRIGGER_UNSPECIFIED
}

func (x *StateAction) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DepartmentId  int64                  `protobuf:"varint,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Steps         []*State               `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *Workflow) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Workflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workflow) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *Workflow) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Workflow) GetSteps() []*State {
	if x != nil {
		return x.Steps
	}
	return nil
}

type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowId    int64                  `protobuf:"varint,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type          StateType              `protobuf:"varint,5,opt,name=type,proto3,enum=workflow.v1.StateType" json:"type,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"` // Здесь лежит JSON представление StepConfiguration
	DurationDays  int32                  `protobuf:"varint,7,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *State) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *State) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *State) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *State) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *State) GetType() StateType {
	if x != nil {
		return x.Type
	}
	return StateType_STATE_TYPE_UNSPECIFIED
}

func (x *State) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *State) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

type Transition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowId    int64                  `protobuf:"varint,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	EventName     string                 `protobuf:"bytes,3,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	FromStateId   int64                  `protobuf:"varint,4,opt,name=from_state_id,json=fromStateId,proto3" json:"from_state_id,omitempty"`
	ToStateId     int64                  `protobuf:"varint,5,opt,name=to_state_id,json=toStateId,proto3" json:"to_state_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transition) Reset() {
	*x = Transition{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transition) ProtoMessage() {}

func (x *Transition) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transition.ProtoReflect.Descriptor instead.
func (*Transition) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *Transition) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transition) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *Transition) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *Transition) GetFromStateId() int64 {
	if x != nil {
		return x.FromStateId
	}
	return 0
}

func (x *Transition) GetToStateId() int64 {
	if x != nil {
		return x.ToStateId
	}
	return 0
}

type CreateWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DepartmentId  int64                  `protobuf:"varint,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowRequest) Reset() {
	*x = CreateWorkflowRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowRequest) ProtoMessage() {}

func (x *CreateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *CreateWorkflowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkflowRequest) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

type GetWorkflowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Criteria:
	//
	//	*GetWorkflowRequest_WorkflowId
	//	*GetWorkflowRequest_Name
	Criteria      isGetWorkflowRequest_Criteria `protobuf_oneof:"criteria"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRequest) Reset() {
	*x = GetWorkflowRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRequest) ProtoMessage() {}

func (x *GetWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{10}
}

func (x *GetWorkflowRequest) GetCriteria() isGetWorkflowRequest_Criteria {
	if x != nil {
		return x.Criteria
	}
	return nil
}

func (x *GetWorkflowRequest) GetWorkflowId() int64 {
	if x != nil {
		if x, ok := x.Criteria.(*GetWorkflowRequest_WorkflowId); ok {
			return x.WorkflowId
		}
	}
	return 0
}

func (x *GetWorkflowRequest) GetName() string {
	if x != nil {
		if x, ok := x.Criteria.(*GetWorkflowRequest_Name); ok {
			return x.Name
		}
	}
	return ""
}

type isGetWorkflowRequest_Criteria interface {
	isGetWorkflowRequest_Criteria()
}

type GetWorkflowRequest_WorkflowId struct {
	WorkflowId int64 `protobuf:"varint,1,opt,name=workflow_id,json=workflowId,proto3,oneof"`
}

type GetWorkflowRequest_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

func (*GetWorkflowRequest_WorkflowId) isGetWorkflowRequest_Criteria() {}

func (*GetWorkflowRequest_Name) isGetWorkflowRequest_Criteria() {}

type ListWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  int64                  `protobuf:"varint,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{11}
}

func (x *ListWorkflowsRequest) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

type ListWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*Workflow            `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{12}
}

func (x *ListWorkflowsResponse) GetWorkflows() []*Workflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

type UpdateWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkflowRequest) Reset() {
	*x = UpdateWorkflowRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkflowRequest) ProtoMessage() {}

func (x *UpdateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateWorkflowRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateWorkflowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkflowRequest) Reset() {
	*x = DeleteWorkflowRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkflowRequest) ProtoMessage() {}

func (x *DeleteWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkflowRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteWorkflowRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    int64                  `protobuf:"varint,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          StateType              `protobuf:"varint,4,opt,name=type,proto3,enum=workflow.v1.StateType" json:"type,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	DurationDays  int32                  `protobuf:"varint,6,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStateRequest) Reset() {
	*x = CreateStateRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStateRequest) ProtoMessage() {}

func (x *CreateStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStateRequest.ProtoReflect.Descriptor instead.
func (*CreateStateRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{15}
}

func (x *CreateStateRequest) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *CreateStateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateStateRequest) GetType() StateType {
	if x != nil {
		return x.Type
	}
	return StateType_STATE_TYPE_UNSPECIFIED
}

func (x *CreateStateRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateStateRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateId       int64                  `protobuf:"varint,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{16}
}

func (x *GetStateRequest) GetStateId() int64 {
	if x != nil {
		return x.StateId
	}
	return 0
}

type ListStatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    int64                  `protobuf:"varint,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStatesRequest) Reset() {
	*x = ListStatesRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStatesRequest) ProtoMessage() {}

func (x *ListStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStatesRequest.ProtoReflect.Descriptor instead.
func (*ListStatesRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{17}
}

func (x *ListStatesRequest) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

type ListStatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        []*State               `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStatesResponse) Reset() {
	*x = ListStatesResponse{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStatesResponse) ProtoMessage() {}

func (x *ListStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStatesResponse.ProtoReflect.Descriptor instead.
func (*ListStatesResponse) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{18}
}

func (x *ListStatesResponse) GetStates() []*State {
	if x != nil {
		return x.States
	}
	return nil
}

type UpdateStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	DurationDays  int32                  `protobuf:"varint,5,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStateRequest) Reset() {
	*x = UpdateStateRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStateRequest) ProtoMessage() {}

func (x *UpdateStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateStateRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateStateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateStateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateStateRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateStateRequest) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

type DeleteStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStateRequest) Reset() {
	*x = DeleteStateRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStateRequest) ProtoMessage() {}

func (x *DeleteStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStateRequest.ProtoReflect.Descriptor instead.
func (*DeleteStateRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteStateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateTransitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    int64                  `protobuf:"varint,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	EventName     string                 `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	FromStateId   int64                  `protobuf:"varint,3,opt,name=from_state_id,json=fromStateId,proto3" json:"from_state_id,omitempty"`
	ToStateId     int64                  `protobuf:"varint,4,opt,name=to_state_id,json=toStateId,proto3" json:"to_state_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransitionRequest) Reset() {
	*x = CreateTransitionRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransitionRequest) ProtoMessage() {}

func (x *CreateTransitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransitionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransitionRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{21}
}

func (x *CreateTransitionRequest) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *CreateTransitionRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *CreateTransitionRequest) GetFromStateId() int64 {
	if x != nil {
		return x.FromStateId
	}
	return 0
}

func (x *CreateTransitionRequest) GetToStateId() int64 {
	if x != nil {
		return x.ToStateId
	}
	return 0
}

type DeleteTransitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransitionRequest) Reset() {
	*x = DeleteTransitionRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransitionRequest) ProtoMessage() {}

func (x *DeleteTransitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransitionRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransitionRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteTransitionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateStateActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateId       int64                  `protobuf:"varint,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	Type          StateAction_ActionType `protobuf:"varint,2,opt,name=type,proto3,enum=workflow.v1.StateAction_ActionType" json:"type,omitempty"`
	Trigger       StateAction_Trigger    `protobuf:"varint,3,opt,name=trigger,proto3,enum=workflow.v1.StateAction_Trigger" json:"trigger,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStateActionRequest) Reset() {
	*x = CreateStateActionRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStateActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStateActionRequest) ProtoMessage() {}

func (x *CreateStateActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStateActionRequest.ProtoReflect.Descriptor instead.
func (*CreateStateActionRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{23}
}

func (x *CreateStateActionRequest) GetStateId() int64 {
	if x != nil {
		return x.StateId
	}
	return 0
}

func (x *CreateStateActionRequest) GetType() StateAction_ActionType {
	if x != nil {
		return x.Type
	}
	return StateAction_ACTION_TYPE_UNSPECIFIED
}

func (x *CreateStateActionRequest) GetTrigger() StateAction_Trigger {
	if x != nil {
		return x.Trigger
	}
	return StateAction_TRIGGER_UNSPECIFIED
}

func (x *CreateStateActionRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type ListStateActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateId       int64                  `protobuf:"varint,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStateActionsRequest) Reset() {
	*x = ListStateActionsRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStateActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStateActionsRequest) ProtoMessage() {}

func (x *ListStateActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStateActionsRequest.ProtoReflect.Descriptor instead.
func (*ListStateActionsRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{24}
}

func (x *ListStateActionsRequest) GetStateId() int64 {
	if x != nil {
		return x.StateId
	}
	return 0
}

type ListStateActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*StateAction         `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStateActionsResponse) Reset() {
	*x = ListStateActionsResponse{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStateActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStateActionsResponse) ProtoMessage() {}

func (x *ListStateActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStateActionsResponse.ProtoReflect.Descriptor instead.
func (*ListStateActionsResponse) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{25}
}

func (x *ListStateActionsResponse) GetActions() []*StateAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type DeleteStateActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStateActionRequest) Reset() {
	*x = DeleteStateActionRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStateActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStateActionRequest) ProtoMessage() {}

func (x *DeleteStateActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStateActionRequest.ProtoReflect.Descriptor instead.
func (*DeleteStateActionRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteStateActionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SetActiveWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    int64                  `protobuf:"varint,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActiveWorkflowRequest) Reset() {
	*x = SetActiveWorkflowRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActiveWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActiveWorkflowRequest) ProtoMessage() {}

func (x *SetActiveWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActiveWorkflowRequest.ProtoReflect.Descriptor instead.
func (*SetActiveWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{27}
}

func (x *SetActiveWorkflowRequest) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

type GetActiveWorkflowByDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  int64                  `protobuf:"varint,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveWorkflowByDepartmentRequest) Reset() {
	*x = GetActiveWorkflowByDepartmentRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveWorkflowByDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveWorkflowByDepartmentRequest) ProtoMessage() {}

func (x *GetActiveWorkflowByDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveWorkflowByDepartmentRequest.ProtoReflect.Descriptor instead.
func (*GetActiveWorkflowByDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{28}
}

func (x *GetActiveWorkflowByDepartmentRequest) GetDepartmentId() int64 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

type GetNextStateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentStateId int64                  `protobuf:"varint,1,opt,name=current_state_id,json=currentStateId,proto3" json:"current_state_id,omitempty"`
	EventName      string                 `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNextStateRequest) Reset() {
	*x = GetNextStateRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextStateRequest) ProtoMessage() {}

func (x *GetNextStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextStateRequest.ProtoReflect.Descriptor instead.
func (*GetNextStateRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{29}
}

func (x *GetNextStateRequest) GetCurrentStateId() int64 {
	if x != nil {
		return x.CurrentStateId
	}
	return 0
}

func (x *GetNextStateRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

type GetStepConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateId       int64                  `protobuf:"varint,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStepConfigurationRequest) Reset() {
	*x = GetStepConfigurationRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStepConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStepConfigurationRequest) ProtoMessage() {}

func (x *GetStepConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStepConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetStepConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{30}
}

func (x *GetStepConfigurationRequest) GetStateId() int64 {
	if x != nil {
		return x.StateId
	}
	return 0
}

var File_workflow_v1_workflow_proto protoreflect.FileDescriptor

const file_workflow_v1_workflow_proto_rawDesc = "" +
	"\n" +
	"\x1aworkflow/v1/workflow.proto\x12\vworkflow.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x02\n" +
	"\x11StepConfiguration\x128\n" +
	"\vteam_config\x18\x01 \x01(\v2\x17.workflow.v1.TeamConfigR\n" +
	"teamConfig\x12D\n" +
	"\x0fdeadline_config\x18\x02 \x01(\v2\x1b.workflow.v1.DeadlineConfigR\x0edeadlineConfig\x128\n" +
	"\vform_schema\x18\x03 \x01(\v2\x17.workflow.v1.FormSchemaR\n" +
	"formSchema\x12J\n" +
	"\x11file_requirements\x18\x04 \x01(\v2\x1d.workflow.v1.FileRequirementsR\x10fileRequirements\x12#\n" +
	"\rallowed_roles\x18\x05 \x03(\tR\fallowedRoles\"a\n" +
	"\n" +
	"TeamConfig\x12\x19\n" +
	"\bmin_size\x18\x01 \x01(\x05R\aminSize\x12\x19\n" +
	"\bmax_size\x18\x02 \x01(\x05R\amaxSize\x12\x1d\n" +
	"\n" +
	"allow_solo\x18\x03 \x01(\bR\tallowSolo\"\x9a\x01\n" +
	"\x0eDeadlineConfig\x12;\n" +
	"\n" +
	"fixed_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tfixedDate\x12'\n" +
	"\x0eduration_hours\x18\x02 \x01(\x05H\x00R\rdurationHours\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezoneB\x06\n" +
	"\x04type\"F\n" +
	"\n" +
	"FormSchema\x12\x17\n" +
	"\aform_id\x18\x01 \x01(\tR\x06formId\x12\x1f\n" +
	"\vjson_schema\x18\x02 \x01(\tR\n" +
	"jsonSchema\"\x84\x01\n" +
	"\x10FileRequirements\x12\x1b\n" +
	"\tmax_files\x18\x01 \x01(\x05R\bmaxFiles\x12-\n" +
	"\x12allowed_extensions\x18\x02 \x03(\tR\x11allowedExtensions\x12$\n" +
	"\x0emax_size_bytes\x18\x03 \x01(\x03R\fmaxSizeBytes\"\x93\x03\n" +
	"\vStateAction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bstate_id\x18\x02 \x01(\x03R\astateId\x127\n" +
	"\x04type\x18\x03 \x01(\x0e2#.workflow.v1.StateAction.ActionTypeR\x04type\x12:\n" +
	"\atrigger\x18\x04 \x01(\x0e2 .workflow.v1.StateAction.TriggerR\atrigger\x12/\n" +
	"\x06config\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06config\"c\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SEND_NOTIFICATION\x10\x01\x12\x0f\n" +
	"\vASSIGN_TASK\x10\x02\x12\x10\n" +
	"\fCALL_WEBHOOK\x10\x03\"N\n" +
	"\aTrigger\x12\x17\n" +
	"\x13TRIGGER_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bON_ENTER\x10\x01\x12\v\n" +
	"\aON_EXIT\x10\x02\x12\x0f\n" +
	"\vON_DEADLINE\x10\x03\"\x9a\x01\n" +
	"\bWorkflow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rdepartment_id\x18\x03 \x01(\x03R\fdepartmentId\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12(\n" +
	"\x05steps\x18\x05 \x03(\v2\x12.workflow.v1.StateR\x05steps\"\xf0\x01\n" +
	"\x05State\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\x03R\n" +
	"workflowId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12*\n" +
	"\x04type\x18\x05 \x01(\x0e2\x16.workflow.v1.StateTypeR\x04type\x12/\n" +
	"\x06config\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06config\x12#\n" +
	"\rduration_days\x18\a \x01(\x05R\fdurationDays\"\xa0\x01\n" +
	"\n" +
	"Transition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\x03R\n" +
	"workflowId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x03 \x01(\tR\teventName\x12\"\n" +
	"\rfrom_state_id\x18\x04 \x01(\x03R\vfromStateId\x12\x1e\n" +
	"\vto_state_id\x18\x05 \x01(\x03R\ttoStateId\"P\n" +
	"\x15CreateWorkflowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\x03R\fdepartmentId\"Y\n" +
	"\x12GetWorkflowRequest\x12!\n" +
	"\vworkflow_id\x18\x01 \x01(\x03H\x00R\n" +
	"workflowId\x12\x14\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04nameB\n" +
	"\n" +
	"\bcriteria\";\n" +
	"\x14ListWorkflowsRequest\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\x03R\fdepartmentId\"L\n" +
	"\x15ListWorkflowsResponse\x123\n" +
	"\tworkflows\x18\x01 \x03(\v2\x15.workflow.v1.WorkflowR\tworkflows\";\n" +
	"\x15UpdateWorkflowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"'\n" +
	"\x15DeleteWorkflowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xed\x01\n" +
	"\x12CreateStateRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\x03R\n" +
	"workflowId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12*\n" +
	"\x04type\x18\x04 \x01(\x0e2\x16.workflow.v1.StateTypeR\x04type\x12/\n" +
	"\x06config\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06config\x12#\n" +
	"\rduration_days\x18\x06 \x01(\x05R\fdurationDays\",\n" +
	"\x0fGetStateRequest\x12\x19\n" +
	"\bstate_id\x18\x01 \x01(\x03R\astateId\"4\n" +
	"\x11ListStatesRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\x03R\n" +
	"workflowId\"@\n" +
	"\x12ListStatesResponse\x12*\n" +
	"\x06states\x18\x01 \x03(\v2\x12.workflow.v1.StateR\x06states\"\xb0\x01\n" +
	"\x12UpdateStateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12/\n" +
	"\x06config\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06config\x12#\n" +
	"\rduration_days\x18\x05 \x01(\x05R\fdurationDays\"$\n" +
	"\x12DeleteStateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x9d\x01\n" +
	"\x17CreateTransitionRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\x03R\n" +
	"workflowId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x12\"\n" +
	"\rfrom_state_id\x18\x03 \x01(\x03R\vfromStateId\x12\x1e\n" +
	"\vto_state_id\x18\x04 \x01(\x03R\ttoStateId\")\n" +
	"\x17DeleteTransitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xdb\x01\n" +
	"\x18CreateStateActionRequest\x12\x19\n" +
	"\bstate_id\x18\x01 \x01(\x03R\astateId\x127\n" +
	"\x04type\x18\x02 \x01(\x0e2#.workflow.v1.StateAction.ActionTypeR\x04type\x12:\n" +
	"\atrigger\x18\x03 \x01(\x0e2 .workflow.v1.StateAction.TriggerR\atrigger\x12/\n" +
	"\x06config\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06config\"4\n" +
	"\x17ListStateActionsRequest\x12\x19\n" +
	"\bstate_id\x18\x01 \x01(\x03R\astateId\"N\n" +
	"\x18ListStateActionsResponse\x122\n" +
	"\aactions\x18\x01 \x03(\v2\x18.workflow.v1.StateActionR\aactions\"*\n" +
	"\x18DeleteStateActionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\";\n" +
	"\x18SetActiveWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\x03R\n" +
	"workflowId\"K\n" +
	"$GetActiveWorkflowByDepartmentRequest\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\x03R\fdepartmentId\"^\n" +
	"\x13GetNextStateRequest\x12(\n" +
	"\x10current_state_id\x18\x01 \x01(\x03R\x0ecurrentStateId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\"8\n" +
	"\x1bGetStepConfigurationRequest\x12\x19\n" +
	"\bstate_id\x18\x01 \x01(\x03R\astateId*\x9e\x01\n" +
	"\tStateType\x12\x1a\n" +
	"\x16STATE_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTEAM_FORMATION\x10\x01\x12\x18\n" +
	"\x14SUPERVISOR_SELECTION\x10\x02\x12\x13\n" +
	"\x0fDOCUMENT_UPLOAD\x10\x03\x12\x10\n" +
	"\fFORM_FILLING\x10\x04\x12\x12\n" +
	"\x0eEXTERNAL_CHECK\x10\x05\x12\f\n" +
	"\bAPPROVAL\x10\x062\x8b\f\n" +
	"\x0fWorkflowService\x12K\n" +
	"\x0eCreateWorkflow\x12\".workflow.v1.CreateWorkflowRequest\x1a\x15.workflow.v1.Workflow\x12E\n" +
	"\vGetWorkflow\x12\x1f.workflow.v1.GetWorkflowRequest\x1a\x15.workflow.v1.Workflow\x12V\n" +
	"\rListWorkflows\x12!.workflow.v1.ListWorkflowsRequest\x1a\".workflow.v1.ListWorkflowsResponse\x12K\n" +
	"\x0eUpdateWorkflow\x12\".workflow.v1.UpdateWorkflowRequest\x1a\x15.workflow.v1.Workflow\x12L\n" +
	"\x0eDeleteWorkflow\x12\".workflow.v1.DeleteWorkflowRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\vCreateState\x12\x1f.workflow.v1.CreateStateRequest\x1a\x12.workflow.v1.State\x12<\n" +
	"\bGetState\x12\x1c.workflow.v1.GetStateRequest\x1a\x12.workflow.v1.State\x12M\n" +
	"\n" +
	"ListStates\x12\x1e.workflow.v1.ListStatesRequest\x1a\x1f.workflow.v1.ListStatesResponse\x12B\n" +
	"\vUpdateState\x12\x1f.workflow.v1.UpdateStateRequest\x1a\x12.workflow.v1.State\x12F\n" +
	"\vDeleteState\x12\x1f.workflow.v1.DeleteStateRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x10CreateTransition\x12$.workflow.v1.CreateTransitionRequest\x1a\x17.workflow.v1.Transition\x12P\n" +
	"\x10DeleteTransition\x12$.workflow.v1.DeleteTransitionRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x11CreateStateAction\x12%.workflow.v1.CreateStateActionRequest\x1a\x18.workflow.v1.StateAction\x12_\n" +
	"\x10ListStateActions\x12$.workflow.v1.ListStateActionsRequest\x1a%.workflow.v1.ListStateActionsResponse\x12R\n" +
	"\x11DeleteStateAction\x12%.workflow.v1.DeleteStateActionRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x11SetActiveWorkflow\x12%.workflow.v1.SetActiveWorkflowRequest\x1a\x15.workflow.v1.Workflow\x12i\n" +
	"\x1dGetActiveWorkflowByDepartment\x121.workflow.v1.GetActiveWorkflowByDepartmentRequest\x1a\x15.workflow.v1.Workflow\x12D\n" +
	"\fGetNextState\x12 .workflow.v1.GetNextStateRequest\x1a\x12.workflow.v1.State\x12`\n" +
	"\x14GetStepConfiguration\x12(.workflow.v1.GetStepConfigurationRequest\x1a\x1e.workflow.v1.StepConfigurationB;Z9github.com/lucky720s/diplomaflow/pkg/protobuf/workflow/v1b\x06proto3"

var (
	file_workflow_v1_workflow_proto_rawDescOnce sync.Once
	file_workflow_v1_workflow_proto_rawDescData []byte
)

func file_workflow_v1_workflow_proto_rawDescGZIP() []byte {
	file_workflow_v1_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_v1_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_v1_workflow_proto_rawDesc), len(file_workflow_v1_workflow_proto_rawDesc)))
	})
	return file_workflow_v1_workflow_proto_rawDescData
}

var file_workflow_v1_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_workflow_v1_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_workflow_v1_workflow_proto_goTypes = []any{
	(StateType)(0),                               // 0: workflow.v1.StateType
	(StateAction_ActionType)(0),                  // 1: workflow.v1.StateAction.ActionType
	(StateAction_Trigger)(0),                     // 2: workflow.v1.StateAction.Trigger
	(*StepConfiguration)(nil),                    // 3: workflow.v1.StepConfiguration
	(*TeamConfig)(nil),                           // 4: workflow.v1.TeamConfig
	(*DeadlineConfig)(nil),                       // 5: workflow.v1.DeadlineConfig
	(*FormSchema)(nil),                           // 6: workflow.v1.FormSchema
	(*FileRequirements)(nil),                     // 7: workflow.v1.FileRequirements
	(*StateAction)(nil),                          // 8: workflow.v1.StateAction
	(*Workflow)(nil),                             // 9: workflow.v1.Workflow
	(*State)(nil),                                // 10: workflow.v1.State
	(*Transition)(nil),                           // 11: workflow.v1.Transition
	(*CreateWorkflowRequest)(nil),                // 12: workflow.v1.CreateWorkflowRequest
	(*GetWorkflowRequest)(nil),                   // 13: workflow.v1.GetWorkflowRequest
	(*ListWorkflowsRequest)(nil),                 // 14: workflow.v1.ListWorkflowsRequest
	(*ListWorkflowsResponse)(nil),                // 15: workflow.v1.ListWorkflowsResponse
	(*UpdateWorkflowRequest)(nil),                // 16: workflow.v1.UpdateWorkflowRequest
	(*DeleteWorkflowRequest)(nil),                // 17: workflow.v1.DeleteWorkflowRequest
	(*CreateStateRequest)(nil),                   // 18: workflow.v1.CreateStateRequest
	(*GetStateRequest)(nil),                      // 19: workflow.v1.GetStateRequest
	(*ListStatesRequest)(nil),                    // 20: workflow.v1.ListStatesRequest
	(*ListStatesResponse)(nil),                   // 21: workflow.v1.ListStatesResponse
	(*UpdateStateRequest)(nil),                   // 22: workflow.v1.UpdateStateRequest
	(*DeleteStateRequest)(nil),                   // 23: workflow.v1.DeleteStateRequest
	(*CreateTransitionRequest)(nil),              // 24: workflow.v1.CreateTransitionRequest
	(*DeleteTransitionRequest)(nil),              // 25: workflow.v1.DeleteTransitionRequest
	(*CreateStateActionRequest)(nil),             // 26: workflow.v1.CreateStateActionRequest
	(*ListStateActionsRequest)(nil),              // 27: workflow.v1.ListStateActionsRequest
	(*ListStateActionsResponse)(nil),             // 28: workflow.v1.ListStateActionsResponse
	(*DeleteStateActionRequest)(nil),             // 29: workflow.v1.DeleteStateActionRequest
	(*SetActiveWorkflowRequest)(nil),             // 30: workflow.v1.SetActiveWorkflowRequest
	(*GetActiveWorkflowByDepartmentRequest)(nil), // 31: workflow.v1.GetActiveWorkflowByDepartmentRequest
	(*GetNextStateRequest)(nil),                  // 32: workflow.v1.GetNextStateRequest
	(*GetStepConfigurationRequest)(nil),          // 33: workflow.v1.GetStepConfigurationRequest
	(*timestamppb.Timestamp)(nil),                // 34: google.protobuf.Timestamp
	(*structpb.Struct)(nil),                      // 35: google.protobuf.Struct
	(*emptypb.Empty)(nil),                        // 36: google.protobuf.Empty
}
var file_workflow_v1_workflow_proto_depIdxs = []int32{
	4,  // 0: workflow.v1.StepConfiguration.team_config:type_name -> workflow.v1.TeamConfig
	5,  // 1: workflow.v1.StepConfiguration.deadline_config:type_name -> workflow.v1.DeadlineConfig
	6,  // 2: workflow.v1.StepConfiguration.form_schema:type_name -> workflow.v1.FormSchema
	7,  // 3: workflow.v1.StepConfiguration.file_requirements:type_name -> workflow.v1.FileRequirements
	34, // 4: workflow.v1.DeadlineConfig.fixed_date:type_name -> google.protobuf.Timestamp
	1,  // 5: workflow.v1.StateAction.type:type_name -> workflow.v1.StateAction.ActionType
	2,  // 6: workflow.v1.StateAction.trigger:type_name -> workflow.v1.StateAction.Trigger
	35, // 7: workflow.v1.StateAction.config:type_name -> google.protobuf.Struct
	10, // 8: workflow.v1.Workflow.steps:type_name -> workflow.v1.State
	0,  // 9: workflow.v1.State.type:type_name -> workflow.v1.StateType
	35, // 10: workflow.v1.State.config:type_name -> google.protobuf.Struct
	9,  // 11: workflow.v1.ListWorkflowsResponse.workflows:type_name -> workflow.v1.Workflow
	0,  // 12: workflow.v1.CreateStateRequest.type:type_name -> workflow.v1.StateType
	35, // 13: workflow.v1.CreateStateRequest.config:type_name -> google.protobuf.Struct
	10, // 14: workflow.v1.ListStatesResponse.states:type_name -> workflow.v1.State
	35, // 15: workflow.v1.UpdateStateRequest.config:type_name -> google.protobuf.Struct
	1,  // 16: workflow.v1.CreateStateActionRequest.type:type_name -> workflow.v1.StateAction.ActionType
	2,  // 17: workflow.v1.CreateStateActionRequest.trigger:type_name -> workflow.v1.StateAction.Trigger
	35, // 18: workflow.v1.CreateStateActionRequest.config:type_name -> google.protobuf.Struct
	8,  // 19: workflow.v1.ListStateActionsResponse.actions:type_name -> workflow.v1.StateAction
	12, // 20: workflow.v1.WorkflowService.CreateWorkflow:input_type -> workflow.v1.CreateWorkflowRequest
	13, // 21: workflow.v1.WorkflowService.GetWorkflow:input_type -> workflow.v1.GetWorkflowRequest
	14, // 22: workflow.v1.WorkflowService.ListWorkflows:input_type -> workflow.v1.ListWorkflowsRequest
	16, // 23: workflow.v1.WorkflowService.UpdateWorkflow:input_type -> workflow.v1.UpdateWorkflowRequest
	17, // 24: workflow.v1.WorkflowService.DeleteWorkflow:input_type -> workflow.v1.DeleteWorkflowRequest
	18, // 25: workflow.v1.WorkflowService.CreateState:input_type -> workflow.v1.CreateStateRequest
	19, // 26: workflow.v1.WorkflowService.GetState:input_type -> workflow.v1.GetStateRequest
	20, // 27: workflow.v1.WorkflowService.ListStates:input_type -> workflow.v1.ListStatesRequest
	22, // 28: workflow.v1.WorkflowService.UpdateState:input_type -> workflow.v1.UpdateStateRequest
	23, // 29: workflow.v1.WorkflowService.DeleteState:input_type -> workflow.v1.DeleteStateRequest
	24, // 30: workflow.v1.WorkflowService.CreateTransition:input_type -> workflow.v1.CreateTransitionRequest
	25, // 31: workflow.v1.WorkflowService.DeleteTransition:input_type -> workflow.v1.DeleteTransitionRequest
	26, // 32: workflow.v1.WorkflowService.CreateStateAction:input_type -> workflow.v1.CreateStateActionRequest
	27, // 33: workflow.v1.WorkflowService.ListStateActions:input_type -> workflow.v1.ListStateActionsRequest
	29, // 34: workflow.v1.WorkflowService.DeleteStateAction:input_type -> workflow.v1.DeleteStateActionRequest
	30, // 35: workflow.v1.WorkflowService.SetActiveWorkflow:input_type -> workflow.v1.SetActiveWorkflowRequest
	31, // 36: workflow.v1.WorkflowService.GetActiveWorkflowByDepartment:input_type -> workflow.v1.GetActiveWorkflowByDepartmentRequest
	32, // 37: workflow.v1.WorkflowService.GetNextState:input_type -> workflow.v1.GetNextStateRequest
	33, // 38: workflow.v1.WorkflowService.GetStepConfiguration:input_type -> workflow.v1.GetStepConfigurationRequest
	9,  // 39: workflow.v1.WorkflowService.CreateWorkflow:output_type -> workflow.v1.Workflow
	9,  // 40: workflow.v1.WorkflowService.GetWorkflow:output_type -> workflow.v1.Workflow
	15, // 41: workflow.v1.WorkflowService.ListWorkflows:output_type -> workflow.v1.ListWorkflowsResponse
	9,  // 42: workflow.v1.WorkflowService.UpdateWorkflow:output_type -> workflow.v1.Workflow
	36, // 43: workflow.v1.WorkflowService.DeleteWorkflow:output_type -> google.protobuf.Empty
	10, // 44: workflow.v1.WorkflowService.CreateState:output_type -> workflow.v1.State
	10, // 45: workflow.v1.WorkflowService.GetState:output_type -> workflow.v1.State
	21, // 46: workflow.v1.WorkflowService.ListStates:output_type -> workflow.v1.ListStatesResponse
	10, // 47: workflow.v1.WorkflowService.UpdateState:output_type -> workflow.v1.State
	36, // 48: workflow.v1.WorkflowService.DeleteState:output_type -> google.protobuf.Empty
	11, // 49: workflow.v1.WorkflowService.CreateTransition:output_type -> workflow.v1.Transition
	36, // 50: workflow.v1.WorkflowService.DeleteTransition:output_type -> google.protobuf.Empty
	8,  // 51: workflow.v1.WorkflowService.CreateStateAction:output_type -> workflow.v1.StateAction
	28, // 52: workflow.v1.WorkflowService.ListStateActions:output_type -> workflow.v1.ListStateActionsResponse
	36, // 53: workflow.v1.WorkflowService.DeleteStateAction:output_type -> google.protobuf.Empty
	9,  // 54: workflow.v1.WorkflowService.SetActiveWorkflow:output_type -> workflow.v1.Workflow
	9,  // 55: workflow.v1.WorkflowService.GetActiveWorkflowByDepartment:output_type -> workflow.v1.Workflow
	10, // 56: workflow.v1.WorkflowService.GetNextState:output_type -> workflow.v1.State
	3,  // 57: workflow.v1.WorkflowService.GetStepConfiguration:output_type -> workflow.v1.StepConfiguration
	39, // [39:58] is the sub-list for method output_type
	20, // [20:39] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_workflow_v1_workflow_proto_init() }
func file_workflow_v1_workflow_proto_init() {
	if File_workflow_v1_workflow_proto != nil {
		return
	}
	file_workflow_v1_workflow_proto_msgTypes[2].OneofWrappers = []any{
		(*DeadlineConfig_FixedDate)(nil),
		(*DeadlineConfig_DurationHours)(nil),
	}
	file_workflow_v1_workflow_proto_msgTypes[10].OneofWrappers = []any{
		(*GetWorkflowRequest_WorkflowId)(nil),
		(*GetWorkflowRequest_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_v1_workflow_proto_rawDesc), len(file_workflow_v1_workflow_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflow_v1_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_v1_workflow_proto_depIdxs,
		EnumInfos:         file_workflow_v1_workflow_proto_enumTypes,
		MessageInfos:      file_workflow_v1_workflow_proto_msgTypes,
	}.Build()
	File_workflow_v1_workflow_proto = out.File
	file_workflow_v1_workflow_proto_goTypes = nil
	file_workflow_v1_workflow_proto_depIdxs = nil
}
