syntax = "proto3";
package workflow.v1;
option go_package = "pkg/protobuf/workflow/v1";

service WorkflowService{
  rpc CreateWorkflow(CreateWorkflowRequest) returns (CreateWorkflowResponse);
  rpc GetWorkflow(GetWorkflowRequest) returns (GetWorkflowResponse);
  rpc CreateStage(CreateStageRequest) returns (CreateStageResponse);
  rpc GetStage(GetStageRequest) returns (GetStageResponse);
  rpc GetNextStage(GetNextStageRequest) returns(GetNextStageResponse);
}

message Workflow{
  int64 id = 1;
  string name = 2;
  int64 department_id = 3;
}
message Stage{
  int64 id = 1;
  string name = 2;
  int64 workflow_id = 3;
  int64 order = 4;
  int64 responsible_role_id = 5;
  int64 deadline_days = 6;
}
message CreateWorkflowRequest{
  string name = 1;
  int64 department_id = 2;
}
message CreateWorkflowResponse{
  Workflow workflow = 1;
}
message GetWorkflowRequest{
  int64 department_id = 1;
}
message GetWorkflowResponse{
  Workflow workflow = 1;
  repeated Stage stages = 2;
}
message CreateStageRequest{
  string name = 1;
  int64 workflow_id = 2;
  int64 order = 3;
  int64 responsible_role_id = 4;
  int64 deadline_days = 5;
}
message CreateStageResponse{
  Stage stage = 1;
}
message GetStageRequest{
  int64 stage_id = 1;
}
message GetStageResponse{
  Stage stage = 1;
}
message GetNextStageRequest{
  int64 current_stage_id = 1;
}
message GetNextStageResponse{
  int64 next_stage_id = 1;
}